[server.pv.addon.voice_messages.component]
voice_message = "<blue><hover:show_text:Click to play>[▶ <argument:0> <argument:1>]"
[server.pv.addon.voice_messages.command]
max_duration_warning = "<yellow>Warning:</yellow> Recording is <argument:0> long. It will stop automatically in <bold><argument:1></bold> seconds."
no_draft = "<red>Nothing to send. Use <click:suggest_command:/vm>/vm</click> to record a voice message."
no_active_recording = "<red>There is no active recording."
recording_timeout = "<red>You didn't say anything in time, recording is cancelled."
draft_saved = "Voice message saved as a draft:<br><argument:0> <argument:1>"
no_active_playback = "<red>There is no active playback."
recording_actionbar = "[<argument:0> / <argument:1>] Recording voice message"
playback_cancel = "<red><hover:show_text:Click to cancel>[Cancel]"
unknown_chat_context = "<red>Unknown chat context."
playback_cancelled = "Playback cancelled."
recording_started = "Recording is started: <argument:0> <argument:1>"
cancel_recording = "<red><hover:show_text:Click to cancel>[Cancel]"
playback_started = "Playback started: <argument:0>"
pv_not_installed = "<red>You don't have <hover:show_text:'https://modrinth.com/plugin/plasmo-voice'><click:open_url:https://modrinth.com/plugin/plasmo-voice><u><blue>Plasmo Voice</blue></u></click></hover> installed."
message_not_found = "<red>Voice message not found."
send_draft = "<yellow><hover:show_text:Click to send>[Send]"
cancel_and_delete_recording = "<red><hover:show_text:Click to cancel>[Cancel & Delete]"
recording_cancelled = "Recording cancelled."
stop_recording = "<yellow><hover:show_text:Click to stop recording>[Stop]"
start_recording = "Speak into \"<argument:0>\" to record a voice message. <argument:2>"
[client.pv.addon.voice_messages]
source_line = "Voice Messages"
