// 本文件由 .team/drafts/art-copy/12-生成tooltips.py 生成，请勿手改。
// 改文案：改 11-描述-80条人工.json（人工 80 条）或 12 里的派生模板，然后重跑生成脚本。
// 作用：给 157 个 KubeJS 自定义物品追加描述行；工具提示只追加，不替换原有行。
// 版式：A 陈述用途 / B 一处反差 / C 玩梗彩蛋（逐条见 .team/drafts/art-copy/13-描述核对表-157条.md）
ItemEvents.modifyTooltips(event => {
  event.add('kubejs:gun_steel_ingot', [Text.of('枪管与机匣的基材，锻造从这里开始。')]);
  event.add('kubejs:gun_steel_sheet', [Text.of('冲压机匣与护木的通用板材。')]);
  event.add('kubejs:spring_steel_ingot', [Text.of('轧成弹簧钢丝前的钢锭。')]);
  event.add('kubejs:spring_steel_sheet', [Text.of('复进簧与弹匣簧的原料。')]);
  event.add('kubejs:spring_wire', [Text.of('绕制各类弹簧的细钢丝。')]);
  event.add('kubejs:recoil_spring', [Text.of('让枪机每一发都回到原位。')]);
  event.add('kubejs:barrel_blank', [Text.of('未钻孔的实心枪管坯料。')]);
  event.add('kubejs:incomplete_barrel', [Text.of('已成型的枪管，还差膛线。')]);
  event.add('kubejs:rifled_barrel', [Text.of('刻好膛线的枪管，可装到机匣上。')]);
  event.add('kubejs:barrel_pistol', [Text.of('短枪管，适合近距离交火。')]);
  event.add('kubejs:barrel_rifle', [Text.of('标准步枪枪管，兼顾射程与操控。')]);
  event.add('kubejs:barrel_heavy', [Text.of('加厚枪管，连射时不易过热。')]);
  event.add('kubejs:barrel_shotgun', [Text.of('大口径滑膛管，装填霰弹。')]);
  event.add('kubejs:launcher_tube', [Text.of('榴弹与火箭的发射管。')]);
  event.add('kubejs:receiver_forging', [Text.of('粗锻机匣毛坯，待切削。')]);
  event.add('kubejs:incomplete_receiver', [Text.of('成型的机匣，还差精加工。')]);
  event.add('kubejs:receiver_machined', [Text.of('精加工完成的机匣，可组装。')]);
  event.add('kubejs:bolt_group', [Text.of('闭锁与抽壳的核心组件。')]);
  event.add('kubejs:firing_pin', [Text.of('撞响底火的那根钢针。')]);
  event.add('kubejs:trigger_group', [Text.of('决定何时开火的组件。')]);
  event.add('kubejs:magazine_body', [Text.of('容纳待发弹药，决定弹容量。')]);
  event.add('kubejs:rail_mount', [Text.of('安装瞄具与配件的基础。')]);
  event.add('kubejs:bipod', [Text.of('两脚架，伏击时把枪架稳。')]);
  event.add('kubejs:polymer_furniture', [Text.of('轻量枪托与护木，成本低。')]);
  event.add('kubejs:carbon_furniture', [Text.of('碳纤维枪托与护木，更轻。')]);
  event.add('kubejs:aluminum_receiver', [Text.of('铝合金机匣，比钢轻。')]);
  event.add('kubejs:brass_blank', [Text.of('冲压弹壳前的黄铜圆坯。')]);
  event.add('kubejs:brass_cup', [Text.of('拉伸成型的黄铜杯体，待修边。')]);
  event.add('kubejs:steel_blank', [Text.of('钢制弹壳坯，成本更低。')]);
  event.add('kubejs:steel_cup', [Text.of('拉伸成型的钢杯体，待修边。')]);
  event.add('kubejs:brass_cup_bright', [Text.of('抛光后的黄铜杯体，成品更亮。')]);
  event.add('kubejs:steel_cup_bright', [Text.of('抛光后的钢杯体，抽壳更顺。')]);
  event.add('kubejs:primer_cup', [Text.of('容纳击发药的小铜壳。')]);
  event.add('kubejs:priming_compound', [Text.of('受撞击即点燃的敏感药剂。')]);
  event.add('kubejs:primer_small', [Text.of('小口径弹药使用的底火。')]);
  event.add('kubejs:primer_large', [Text.of('大口径弹药使用的底火。')]);
  event.add('kubejs:primer_shotgun', [Text.of('霰弹壳使用的大号底火。')]);
  event.add('kubejs:smokeless_powder', [Text.of('现代弹药的主发射药，烟少。')]);
  event.add('kubejs:black_powder', [Text.of('老式火药，烟大但管用。')]);
  event.add('kubejs:lead_core', [Text.of('软质铅芯，适合普通弹头。')]);
  event.add('kubejs:tungsten_core', [Text.of('高硬度钨芯，穿甲弹的关键。')]);
  event.add('kubejs:proj_pistol', [Text.of('手枪弹使用的短弹头。')]);
  event.add('kubejs:proj_mag', [Text.of('装药更多，威力更大。')]);
  event.add('kubejs:proj_mag_heavy', [Text.of('加重马格南弹头，后坐更猛。')]);
  event.add('kubejs:proj_ap_small', [Text.of('小口径穿甲弹头，专治护甲。')]);
  event.add('kubejs:proj_rifle', [Text.of('步枪口径的标准弹头。')]);
  event.add('kubejs:proj_rifle_heavy', [Text.of('加重步枪弹头，远距离留存更好。')]);
  event.add('kubejs:proj_sniper', [Text.of('为远距离精确射击设计。')]);
  event.add('kubejs:proj_heavy_ap', [Text.of('重型穿甲弹头，正面硬碰硬。')]);
  event.add('kubejs:proj_heavy_lead', [Text.of('重型铅芯弹头，止动力强。')]);
  event.add('kubejs:proj_shot', [Text.of('一发霰弹里的一堆小铅丸。')]);
  event.add('kubejs:proj_grenade40', [Text.of('40mm 榴弹的战斗部。')]);
  event.add('kubejs:proj_rocket', [Text.of('火箭弹的战斗部，撞上就炸。')]);
  event.add('kubejs:shot_hull', [Text.of('装药、弹丸与底火的壳筒。')]);
  event.add('kubejs:explosive_filler', [Text.of('填充战斗部的高爆炸药。')]);
  event.add('kubejs:shaped_charge', [Text.of('金属射流的来源，破甲用。')]);
  event.add('kubejs:bomb_casing', [Text.of('等待装药的炸弹壳体。')]);
  event.add('kubejs:bomb_casing_filled', [Text.of('已填装炸药的炸弹壳体。')]);
  event.add('kubejs:warhead_small', [Text.of('小型战斗部，装药量有限。')]);
  event.add('kubejs:warhead_medium', [Text.of('中型战斗部，威力适中。')]);
  event.add('kubejs:warhead_heavy', [Text.of('重型战斗部，一发一座掩体。')]);
  event.add('kubejs:rocket_motor', [Text.of('推进火箭弹的固体发动机。')]);
  event.add('kubejs:guidance_module', [Text.of('修正弹道，让弹药自己找路。')]);
  event.add('kubejs:seeker_head', [Text.of('锁定目标的导引传感器。')]);
  event.add('kubejs:fuze', [Text.of('决定何时引爆的安全件。')]);
  event.add('kubejs:tnt_filler', [Text.of('配方写在罐上，后果写在墙上。')]);
  event.add('kubejs:drone_frame', [Text.of('机身够轻，才飞得够远，也才回得来。')]);
  event.add('kubejs:drone_motor', [Text.of('它一转起来，你就暴露了。')]);
  event.add('kubejs:optic_lens', [Text.of('磨得够细，世界就够清楚。')]);
  event.add('kubejs:optic_tube', [Text.of('把镜片固定在该在的位置。')]);
  event.add('kubejs:suppressor_baffle', [Text.of('一层碗，把枪声按回管子里。')]);
  event.add('kubejs:magnetic_sensor', [Text.of('金属靠近之前，它先紧张。')]);
  event.add('kubejs:pressure_plate_kit', [Text.of('踩上去的那一刻，它才说话。')]);
  event.add('kubejs:gauze', [Text.of('先缠上，疼是之后的事。')]);
  event.add('kubejs:antiseptic', [Text.of('杀菌的时候疼一下，总比烂掉强。')]);
  event.add('kubejs:splint', [Text.of('腿断了，路还得走。')]);
  event.add('kubejs:ballistic_plate', [Text.of('它替你挨那一下，然后退休。')]);
  event.add('kubejs:composite_plate', [Text.of('叠得越多，你越敢往前站。')]);
  event.add('kubejs:filter_canister', [Text.of('进去的是毒气，出来的是苟活。')]);
  event.add('kubejs:nv_tube', [Text.of('天黑不是问题，看不见才是。')]);
  event.add('kubejs:incomplete_aa12', [Text.of('霰弹枪半成品，闭锁面还没磨。')]);
  event.add('kubejs:incomplete_ai_awp', [Text.of('狙击枪半成品，公差还没磨到位。')]);
  event.add('kubejs:incomplete_ak47', [Text.of('步枪半成品，还差精加工与装配。')]);
  event.add('kubejs:incomplete_aug', [Text.of('步枪半成品，还差精加工与装配。')]);
  event.add('kubejs:incomplete_b93r', [Text.of('手枪半成品，就差最后的装配工序。')]);
  event.add('kubejs:incomplete_cz75', [Text.of('手枪半成品，就差最后的装配工序。')]);
  event.add('kubejs:incomplete_db_long', [Text.of('霰弹枪半成品，闭锁面还没磨。')]);
  event.add('kubejs:incomplete_db_short', [Text.of('霰弹枪半成品，闭锁面还没磨。')]);
  event.add('kubejs:incomplete_deagle', [Text.of('手枪半成品，就差最后的装配工序。')]);
  event.add('kubejs:incomplete_deagle_golden', [Text.of('手枪半成品，就差最后的装配工序。')]);
  event.add('kubejs:incomplete_fn_evolys', [Text.of('机枪半成品，还差供弹机构。')]);
  event.add('kubejs:incomplete_fn_fal', [Text.of('步枪半成品，还差精加工与装配。')]);
  event.add('kubejs:incomplete_g36k', [Text.of('步枪半成品，还差精加工与装配。')]);
  event.add('kubejs:incomplete_glock_17', [Text.of('手枪半成品，就差最后的装配工序。')]);
  event.add('kubejs:incomplete_hk416d', [Text.of('步枪半成品，还差精加工与装配。')]);
  event.add('kubejs:incomplete_hk_g3', [Text.of('步枪半成品，还差精加工与装配。')]);
  event.add('kubejs:incomplete_hk_mk23', [Text.of('手枪半成品，就差最后的装配工序。')]);
  event.add('kubejs:incomplete_hk_mp5a5', [Text.of('冲锋枪半成品，弹匣井还没铣完。')]);
  event.add('kubejs:incomplete_kar98', [Text.of('步枪半成品，还差精加工与装配。')]);
  event.add('kubejs:incomplete_lonetrail', [Text.of('手枪半成品，就差最后的装配工序。')]);
  event.add('kubejs:incomplete_m1014', [Text.of('霰弹枪半成品，闭锁面还没磨。')]);
  event.add('kubejs:incomplete_m107', [Text.of('狙击枪半成品，公差还没磨到位。')]);
  event.add('kubejs:incomplete_m16a1', [Text.of('步枪半成品，还差精加工与装配。')]);
  event.add('kubejs:incomplete_m16a4', [Text.of('步枪半成品，还差精加工与装配。')]);
  event.add('kubejs:incomplete_m1911', [Text.of('手枪半成品，就差最后的装配工序。')]);
  event.add('kubejs:incomplete_m249', [Text.of('机枪半成品，还差供弹机构。')]);
  event.add('kubejs:incomplete_m320', [Text.of('发射器半成品，还差发射管。')]);
  event.add('kubejs:incomplete_m4a1', [Text.of('步枪半成品，还差精加工与装配。')]);
  event.add('kubejs:incomplete_m700', [Text.of('狙击枪半成品，公差还没磨到位。')]);
  event.add('kubejs:incomplete_m870', [Text.of('霰弹枪半成品，闭锁面还没磨。')]);
  event.add('kubejs:incomplete_m95', [Text.of('狙击枪半成品，公差还没磨到位。')]);
  event.add('kubejs:incomplete_m9a4', [Text.of('手枪半成品，就差最后的装配工序。')]);
  event.add('kubejs:incomplete_minigun', [Text.of('机枪半成品，还差供弹机构。')]);
  event.add('kubejs:incomplete_mk14', [Text.of('步枪半成品，还差精加工与装配。')]);
  event.add('kubejs:incomplete_p320', [Text.of('手枪半成品，就差最后的装配工序。')]);
  event.add('kubejs:incomplete_p90', [Text.of('冲锋枪半成品，弹匣井还没铣完。')]);
  event.add('kubejs:incomplete_qbz_191', [Text.of('步枪半成品，还差精加工与装配。')]);
  event.add('kubejs:incomplete_qbz_95', [Text.of('步枪半成品，还差精加工与装配。')]);
  event.add('kubejs:incomplete_rhino357', [Text.of('手枪半成品，就差最后的装配工序。')]);
  event.add('kubejs:incomplete_rpg7', [Text.of('发射器半成品，还差发射管。')]);
  event.add('kubejs:incomplete_rpk', [Text.of('机枪半成品，还差供弹机构。')]);
  event.add('kubejs:incomplete_scar_h', [Text.of('步枪半成品，还差精加工与装配。')]);
  event.add('kubejs:incomplete_scar_l', [Text.of('步枪半成品，还差精加工与装配。')]);
  event.add('kubejs:incomplete_sks_tactical', [Text.of('步枪半成品，还差精加工与装配。')]);
  event.add('kubejs:incomplete_spas_12', [Text.of('霰弹枪半成品，闭锁面还没磨。')]);
  event.add('kubejs:incomplete_spr15hb', [Text.of('狙击枪半成品，公差还没磨到位。')]);
  event.add('kubejs:incomplete_springfield1873', [Text.of('步枪半成品，还差精加工与装配。')]);
  event.add('kubejs:incomplete_taurus500', [Text.of('手枪半成品，就差最后的装配工序。')]);
  event.add('kubejs:incomplete_taurus943', [Text.of('手枪半成品，就差最后的装配工序。')]);
  event.add('kubejs:incomplete_timeless50', [Text.of('手枪半成品，就差最后的装配工序。')]);
  event.add('kubejs:incomplete_type_81', [Text.of('步枪半成品，还差精加工与装配。')]);
  event.add('kubejs:incomplete_ump45', [Text.of('冲锋枪半成品，弹匣井还没铣完。')]);
  event.add('kubejs:incomplete_uzi', [Text.of('冲锋枪半成品，弹匣井还没铣完。')]);
  event.add('kubejs:incomplete_vector45', [Text.of('冲锋枪半成品，弹匣井还没铣完。')]);
  event.add('kubejs:case_12g', [Text.of('12 号口径 空弹壳，待装底火。')]);
  event.add('kubejs:case_22wmr', [Text.of('.22 WMR 空弹壳，待装底火。')]);
  event.add('kubejs:case_308', [Text.of('.308 温彻斯特 空弹壳，待装底火。')]);
  event.add('kubejs:case_30_06', [Text.of('.30-06 空弹壳，待装底火。')]);
  event.add('kubejs:case_338', [Text.of('.338 拉普马格南 空弹壳，待装底火。')]);
  event.add('kubejs:case_357mag', [Text.of('.357 马格南 空弹壳，待装底火。')]);
  event.add('kubejs:case_40mm', [Text.of('40mm 空弹壳，待装底火。')]);
  event.add('kubejs:case_45_70', [Text.of('.45-70 空弹壳，待装底火。')]);
  event.add('kubejs:case_45acp', [Text.of('.45 ACP 空弹壳，待装底火。')]);
  event.add('kubejs:case_46x30', [Text.of('4.6x30mm 空弹壳，待装底火。')]);
  event.add('kubejs:case_500mag', [Text.of('.500 马格南 空弹壳，待装底火。')]);
  event.add('kubejs:case_50ae', [Text.of('.50 AE 空弹壳，待装底火。')]);
  event.add('kubejs:case_50bmg', [Text.of('.50 BMG 空弹壳，待装底火。')]);
  event.add('kubejs:case_545x39', [Text.of('5.45x39mm 空弹壳，待装底火。')]);
  event.add('kubejs:case_556x45', [Text.of('5.56x45mm 空弹壳，待装底火。')]);
  event.add('kubejs:case_57x28', [Text.of('5.7x28mm 空弹壳，待装底火。')]);
  event.add('kubejs:case_58x42', [Text.of('5.8x42mm 空弹壳，待装底火。')]);
  event.add('kubejs:case_68x51fury', [Text.of('6.8x51mm 空弹壳，待装底火。')]);
  event.add('kubejs:case_762x25', [Text.of('7.62x25mm 空弹壳，待装底火。')]);
  event.add('kubejs:case_762x39', [Text.of('7.62x39mm 空弹壳，待装底火。')]);
  event.add('kubejs:case_762x54', [Text.of('7.62x54mm 空弹壳，待装底火。')]);
  event.add('kubejs:case_792x57', [Text.of('8mm 毛瑟 空弹壳，待装底火。')]);
  event.add('kubejs:case_9mm', [Text.of('9mm 空弹壳，待装底火。')]);
});
