// priority: 1000
// ============================================================================
//  本文件由 kubejs/_recon/gen_js.py 自动生成 —— 请勿手改，改设计表后重跑脚本。
//  内容：TACZ 枪/弹/配件清单、口径设计表、枪械参数表、MW(面包军火库) 物品表。
// ============================================================================

var MZ_CAL = {
  '12g': { ammo: 'tacz:12g', case: 'hull', cups: 2, powder: 2, proj: 'shot', primer: 'shotgun', batch: 6, cls: 'shotgun' },
  '22wmr': { ammo: 'tacz:22wmr', case: 'brass', cups: 1, powder: 1, proj: 'pistol', primer: 'small', batch: 16, cls: 'rimfire' },
  '308': { ammo: 'tacz:308', case: 'brass', cups: 3, powder: 3, proj: 'rifle_heavy', primer: 'large', batch: 8, cls: 'full_power' },
  '30_06': { ammo: 'tacz:30_06', case: 'brass', cups: 3, powder: 3, proj: 'rifle_heavy', primer: 'large', batch: 8, cls: 'full_power' },
  '338': { ammo: 'tacz:338', case: 'brass', cups: 5, powder: 5, proj: 'sniper', primer: 'large', batch: 6, cls: 'magnum' },
  '357mag': { ammo: 'tacz:357mag', case: 'brass', cups: 2, powder: 2, proj: 'mag', primer: 'small', batch: 8, cls: 'pistol' },
  '40mm': { ammo: 'tacz:40mm', case: 'steel', cups: 4, powder: 4, proj: 'grenade40', primer: 'large', batch: 2, cls: 'launcher' },
  '45_70': { ammo: 'tacz:45_70', case: 'brass', cups: 3, powder: 3, proj: 'heavy_lead', primer: 'large', batch: 8, cls: 'black_powder' },
  '45acp': { ammo: 'tacz:45acp', case: 'brass', cups: 1, powder: 1, proj: 'pistol', primer: 'large', batch: 12, cls: 'pistol' },
  '46x30': { ammo: 'tacz:46x30', case: 'brass', cups: 1, powder: 1, proj: 'ap_small', primer: 'small', batch: 12, cls: 'pdw' },
  '500mag': { ammo: 'tacz:500mag', case: 'brass', cups: 4, powder: 4, proj: 'mag_heavy', primer: 'large', batch: 4, cls: 'pistol' },
  '50ae': { ammo: 'tacz:50ae', case: 'brass', cups: 3, powder: 3, proj: 'mag', primer: 'large', batch: 6, cls: 'pistol' },
  '50bmg': { ammo: 'tacz:50bmg', case: 'brass', cups: 8, powder: 8, proj: 'heavy_ap', primer: 'large', batch: 4, cls: 'anti_materiel' },
  '545x39': { ammo: 'tacz:545x39', case: 'steel', cups: 2, powder: 2, proj: 'rifle', primer: 'small', batch: 10, cls: 'intermediate' },
  '556x45': { ammo: 'tacz:556x45', case: 'brass', cups: 2, powder: 2, proj: 'rifle', primer: 'small', batch: 10, cls: 'intermediate' },
  '57x28': { ammo: 'tacz:57x28', case: 'brass', cups: 1, powder: 1, proj: 'ap_small', primer: 'small', batch: 12, cls: 'pdw' },
  '58x42': { ammo: 'tacz:58x42', case: 'steel', cups: 2, powder: 2, proj: 'rifle', primer: 'small', batch: 10, cls: 'intermediate' },
  '68x51fury': { ammo: 'tacz:68x51fury', case: 'brass', cups: 3, powder: 3, proj: 'rifle_heavy', primer: 'large', batch: 8, cls: 'full_power' },
  '762x25': { ammo: 'tacz:762x25', case: 'steel', cups: 1, powder: 1, proj: 'pistol', primer: 'small', batch: 12, cls: 'pistol' },
  '762x39': { ammo: 'tacz:762x39', case: 'steel', cups: 2, powder: 2, proj: 'rifle', primer: 'large', batch: 10, cls: 'intermediate' },
  '762x54': { ammo: 'tacz:762x54', case: 'steel', cups: 4, powder: 4, proj: 'rifle_heavy', primer: 'large', batch: 8, cls: 'full_power' },
  '792x57': { ammo: 'tacz:792x57', case: 'brass', cups: 4, powder: 4, proj: 'rifle_heavy', primer: 'large', batch: 8, cls: 'full_power' },
  '9mm': { ammo: 'tacz:9mm', case: 'brass', cups: 1, powder: 1, proj: 'pistol', primer: 'small', batch: 12, cls: 'pistol' },
  'rpg_rocket': { ammo: 'tacz:rpg_rocket', case: 'none', cups: 0, powder: 0, proj: 'rocket', primer: 'none', batch: 1, cls: 'rocket' },
}

var MZ_GUNS = [
  { id: 'tacz:aa12', name: 'aa12', ammo: 'tacz:12g', cls: 'shotgun', tier: 3, barrel: 'shotgun', mag: 3, stock: 2, rail: 1, grip: 1, bipod: 0, steel: 5, sheet: 3, spring: 1, extra: 0 },
  { id: 'tacz:ai_awp', name: 'ai_awp', ammo: 'tacz:338', cls: 'sniper', tier: 5, barrel: 'heavy', mag: 1, stock: 3, rail: 2, grip: 0, bipod: 1, steel: 5, sheet: 4, spring: 1, extra: 1 },
  { id: 'tacz:ak47', name: 'ak47', ammo: 'tacz:762x39', cls: 'rifle', tier: 2, barrel: 'rifle', mag: 2, stock: 2, rail: 1, grip: 0, bipod: 0, steel: 4, sheet: 2, spring: 1, extra: 1 },
  { id: 'tacz:aug', name: 'aug', ammo: 'tacz:556x45', cls: 'rifle', tier: 2, barrel: 'rifle', mag: 2, stock: 1, rail: 1, grip: 1, bipod: 0, steel: 4, sheet: 2, spring: 1, extra: 1 },
  { id: 'tacz:b93r', name: 'b93r', ammo: 'tacz:9mm', cls: 'pistol', tier: 2, barrel: 'pistol', mag: 1, stock: 0, rail: 0, grip: 1, bipod: 0, steel: 4, sheet: 2, spring: 1, extra: 0 },
  { id: 'tacz:cz75', name: 'cz75', ammo: 'tacz:9mm', cls: 'pistol', tier: 1, barrel: 'pistol', mag: 1, stock: 0, rail: 0, grip: 1, bipod: 0, steel: 3, sheet: 2, spring: 1, extra: 0 },
  { id: 'tacz:db_long', name: 'db_long', ammo: 'tacz:12g', cls: 'shotgun', tier: 1, barrel: 'shotgun', mag: 0, stock: 3, rail: 0, grip: 0, bipod: 0, steel: 3, sheet: 2, spring: 1, extra: 0 },
  { id: 'tacz:db_short', name: 'db_short', ammo: 'tacz:12g', cls: 'shotgun', tier: 1, barrel: 'shotgun', mag: 0, stock: 2, rail: 0, grip: 0, bipod: 0, steel: 3, sheet: 2, spring: 1, extra: 0 },
  { id: 'tacz:deagle', name: 'deagle', ammo: 'tacz:50ae', cls: 'pistol', tier: 2, barrel: 'pistol', mag: 1, stock: 0, rail: 1, grip: 1, bipod: 0, steel: 4, sheet: 2, spring: 1, extra: 0 },
  { id: 'tacz:deagle_golden', name: 'deagle_golden', ammo: 'tacz:357mag', cls: 'pistol', tier: 2, barrel: 'pistol', mag: 1, stock: 0, rail: 1, grip: 1, bipod: 0, steel: 5, sheet: 2, spring: 1, extra: 0 },
  { id: 'tacz:fn_evolys', name: 'fn_evolys', ammo: 'tacz:308', cls: 'mg', tier: 4, barrel: 'heavy', mag: 3, stock: 2, rail: 2, grip: 1, bipod: 1, steel: 5, sheet: 3, spring: 2, extra: 3 },
  { id: 'tacz:fn_fal', name: 'fn_fal', ammo: 'tacz:308', cls: 'rifle', tier: 4, barrel: 'rifle', mag: 2, stock: 3, rail: 1, grip: 0, bipod: 0, steel: 5, sheet: 3, spring: 1, extra: 1 },
  { id: 'tacz:g36k', name: 'g36k', ammo: 'tacz:556x45', cls: 'rifle', tier: 3, barrel: 'rifle', mag: 2, stock: 1, rail: 1, grip: 1, bipod: 0, steel: 5, sheet: 3, spring: 1, extra: 1 },
  { id: 'tacz:glock_17', name: 'glock_17', ammo: 'tacz:9mm', cls: 'pistol', tier: 1, barrel: 'pistol', mag: 1, stock: 0, rail: 1, grip: 1, bipod: 0, steel: 3, sheet: 2, spring: 1, extra: 0 },
  { id: 'tacz:hk416d', name: 'hk416d', ammo: 'tacz:556x45', cls: 'rifle', tier: 3, barrel: 'rifle', mag: 2, stock: 2, rail: 2, grip: 1, bipod: 0, steel: 5, sheet: 3, spring: 1, extra: 1 },
  { id: 'tacz:hk_g3', name: 'hk_g3', ammo: 'tacz:308', cls: 'rifle', tier: 3, barrel: 'rifle', mag: 2, stock: 3, rail: 1, grip: 0, bipod: 0, steel: 6, sheet: 3, spring: 1, extra: 1 },
  { id: 'tacz:hk_mk23', name: 'hk_mk23', ammo: 'tacz:45acp', cls: 'pistol', tier: 2, barrel: 'pistol', mag: 1, stock: 0, rail: 1, grip: 1, bipod: 0, steel: 6, sheet: 2, spring: 1, extra: 0 },
  { id: 'tacz:hk_mp5a5', name: 'hk_mp5a5', ammo: 'tacz:9mm', cls: 'smg', tier: 2, barrel: 'pistol', mag: 2, stock: 1, rail: 1, grip: 1, bipod: 0, steel: 4, sheet: 2, spring: 1, extra: 1 },
  { id: 'tacz:kar98', name: 'kar98', ammo: 'tacz:792x57', cls: 'sniper', tier: 3, barrel: 'heavy', mag: 0, stock: 3, rail: 1, grip: 0, bipod: 1, steel: 5, sheet: 3, spring: 1, extra: 1 },
  { id: 'tacz:lonetrail', name: 'lonetrail', ammo: 'tacz:30_06', cls: 'pistol', tier: 3, barrel: 'pistol', mag: 1, stock: 0, rail: 2, grip: 1, bipod: 0, steel: 5, sheet: 3, spring: 1, extra: 0 },
  { id: 'tacz:m1014', name: 'm1014', ammo: 'tacz:12g', cls: 'shotgun', tier: 3, barrel: 'shotgun', mag: 1, stock: 2, rail: 1, grip: 1, bipod: 0, steel: 5, sheet: 3, spring: 1, extra: 0 },
  { id: 'tacz:m107', name: 'm107', ammo: 'tacz:50bmg', cls: 'sniper', tier: 5, barrel: 'heavy', mag: 2, stock: 3, rail: 2, grip: 1, bipod: 1, steel: 5, sheet: 4, spring: 1, extra: 1 },
  { id: 'tacz:m16a1', name: 'm16a1', ammo: 'tacz:556x45', cls: 'rifle', tier: 2, barrel: 'rifle', mag: 2, stock: 3, rail: 0, grip: 0, bipod: 0, steel: 4, sheet: 2, spring: 1, extra: 1 },
  { id: 'tacz:m16a4', name: 'm16a4', ammo: 'tacz:556x45', cls: 'rifle', tier: 2, barrel: 'rifle', mag: 2, stock: 3, rail: 1, grip: 0, bipod: 0, steel: 4, sheet: 2, spring: 1, extra: 1 },
  { id: 'tacz:m1911', name: 'm1911', ammo: 'tacz:45acp', cls: 'pistol', tier: 1, barrel: 'pistol', mag: 1, stock: 0, rail: 0, grip: 1, bipod: 0, steel: 5, sheet: 2, spring: 1, extra: 0 },
  { id: 'tacz:m249', name: 'm249', ammo: 'tacz:556x45', cls: 'mg', tier: 4, barrel: 'heavy', mag: 3, stock: 2, rail: 1, grip: 0, bipod: 1, steel: 5, sheet: 3, spring: 2, extra: 3 },
  { id: 'tacz:m320', name: 'm320', ammo: 'tacz:40mm', cls: 'rpg', tier: 3, barrel: 'tube', mag: 0, stock: 0, rail: 1, grip: 1, bipod: 0, steel: 5, sheet: 3, spring: 1, extra: 2 },
  { id: 'tacz:m4a1', name: 'm4a1', ammo: 'tacz:556x45', cls: 'rifle', tier: 2, barrel: 'rifle', mag: 2, stock: 1, rail: 2, grip: 1, bipod: 0, steel: 4, sheet: 2, spring: 1, extra: 1 },
  { id: 'tacz:m700', name: 'm700', ammo: 'tacz:30_06', cls: 'sniper', tier: 2, barrel: 'heavy', mag: 1, stock: 3, rail: 2, grip: 0, bipod: 1, steel: 4, sheet: 2, spring: 1, extra: 1 },
  { id: 'tacz:m870', name: 'm870', ammo: 'tacz:12g', cls: 'shotgun', tier: 2, barrel: 'shotgun', mag: 1, stock: 3, rail: 0, grip: 0, bipod: 0, steel: 4, sheet: 2, spring: 1, extra: 0 },
  { id: 'tacz:m95', name: 'm95', ammo: 'tacz:50bmg', cls: 'sniper', tier: 5, barrel: 'heavy', mag: 1, stock: 3, rail: 2, grip: 0, bipod: 1, steel: 6, sheet: 4, spring: 1, extra: 1 },
  { id: 'tacz:m9a4', name: 'm9a4', ammo: 'tacz:9mm', cls: 'pistol', tier: 1, barrel: 'pistol', mag: 1, stock: 0, rail: 1, grip: 1, bipod: 0, steel: 7, sheet: 2, spring: 1, extra: 0 },
  { id: 'tacz:minigun', name: 'minigun', ammo: 'tacz:308', cls: 'mg', tier: 5, barrel: 'heavy', mag: 3, stock: 0, rail: 0, grip: 0, bipod: 0, steel: 5, sheet: 4, spring: 2, extra: 5 },
  { id: 'tacz:mk14', name: 'mk14', ammo: 'tacz:308', cls: 'rifle', tier: 3, barrel: 'heavy', mag: 2, stock: 3, rail: 2, grip: 1, bipod: 1, steel: 5, sheet: 3, spring: 1, extra: 1 },
  { id: 'tacz:p320', name: 'p320', ammo: 'tacz:45acp', cls: 'pistol', tier: 2, barrel: 'pistol', mag: 1, stock: 0, rail: 1, grip: 1, bipod: 0, steel: 8, sheet: 2, spring: 1, extra: 0 },
  { id: 'tacz:p90', name: 'p90', ammo: 'tacz:57x28', cls: 'smg', tier: 3, barrel: 'pistol', mag: 3, stock: 1, rail: 2, grip: 1, bipod: 0, steel: 5, sheet: 3, spring: 1, extra: 1 },
  { id: 'tacz:qbz_191', name: 'qbz_191', ammo: 'tacz:58x42', cls: 'rifle', tier: 3, barrel: 'rifle', mag: 2, stock: 2, rail: 1, grip: 1, bipod: 0, steel: 5, sheet: 3, spring: 1, extra: 1 },
  { id: 'tacz:qbz_95', name: 'qbz_95', ammo: 'tacz:58x42', cls: 'rifle', tier: 2, barrel: 'rifle', mag: 2, stock: 1, rail: 1, grip: 1, bipod: 0, steel: 5, sheet: 2, spring: 1, extra: 1 },
  { id: 'tacz:rhino357', name: 'rhino357', ammo: 'tacz:357mag', cls: 'pistol', tier: 2, barrel: 'pistol', mag: 0, stock: 0, rail: 1, grip: 1, bipod: 0, steel: 4, sheet: 2, spring: 1, extra: 0 },
  { id: 'tacz:rpg7', name: 'rpg7', ammo: 'tacz:rpg_rocket', cls: 'rpg', tier: 3, barrel: 'tube', mag: 0, stock: 0, rail: 0, grip: 1, bipod: 0, steel: 5, sheet: 3, spring: 1, extra: 2 },
  { id: 'tacz:rpk', name: 'rpk', ammo: 'tacz:762x39', cls: 'mg', tier: 3, barrel: 'heavy', mag: 3, stock: 2, rail: 1, grip: 0, bipod: 1, steel: 6, sheet: 3, spring: 2, extra: 3 },
  { id: 'tacz:scar_h', name: 'scar_h', ammo: 'tacz:308', cls: 'rifle', tier: 3, barrel: 'heavy', mag: 2, stock: 2, rail: 2, grip: 1, bipod: 0, steel: 6, sheet: 3, spring: 1, extra: 1 },
  { id: 'tacz:scar_l', name: 'scar_l', ammo: 'tacz:556x45', cls: 'rifle', tier: 2, barrel: 'rifle', mag: 2, stock: 2, rail: 2, grip: 1, bipod: 0, steel: 4, sheet: 2, spring: 1, extra: 1 },
  { id: 'tacz:sks_tactical', name: 'sks_tactical', ammo: 'tacz:762x39', cls: 'rifle', tier: 2, barrel: 'rifle', mag: 1, stock: 3, rail: 1, grip: 1, bipod: 1, steel: 4, sheet: 2, spring: 1, extra: 1 },
  { id: 'tacz:spas_12', name: 'spas_12', ammo: 'tacz:12g', cls: 'shotgun', tier: 4, barrel: 'shotgun', mag: 1, stock: 2, rail: 1, grip: 1, bipod: 0, steel: 6, sheet: 3, spring: 1, extra: 0 },
  { id: 'tacz:spr15hb', name: 'spr15hb', ammo: 'tacz:556x45', cls: 'rifle', tier: 3, barrel: 'heavy', mag: 2, stock: 3, rail: 2, grip: 1, bipod: 1, steel: 6, sheet: 3, spring: 1, extra: 1 },
  { id: 'tacz:springfield1873', name: 'springfield1873', ammo: 'tacz:45_70', cls: 'sniper', tier: 1, barrel: 'heavy', mag: 0, stock: 3, rail: 1, grip: 0, bipod: 0, steel: 3, sheet: 2, spring: 1, extra: 1 },
  { id: 'tacz:taurus500', name: 'taurus500', ammo: 'tacz:500mag', cls: 'pistol', tier: 4, barrel: 'pistol', mag: 0, stock: 0, rail: 1, grip: 1, bipod: 0, steel: 5, sheet: 3, spring: 1, extra: 0 },
  { id: 'tacz:taurus943', name: 'taurus943', ammo: 'tacz:22wmr', cls: 'pistol', tier: 1, barrel: 'pistol', mag: 0, stock: 0, rail: 0, grip: 1, bipod: 0, steel: 3, sheet: 2, spring: 1, extra: 0 },
  { id: 'tacz:timeless50', name: 'timeless50', ammo: 'tacz:50ae', cls: 'pistol', tier: 2, barrel: 'pistol', mag: 1, stock: 0, rail: 0, grip: 1, bipod: 0, steel: 6, sheet: 2, spring: 1, extra: 0 },
  { id: 'tacz:type_81', name: 'type_81', ammo: 'tacz:762x39', cls: 'rifle', tier: 2, barrel: 'rifle', mag: 2, stock: 2, rail: 1, grip: 1, bipod: 0, steel: 4, sheet: 2, spring: 1, extra: 1 },
  { id: 'tacz:ump45', name: 'ump45', ammo: 'tacz:45acp', cls: 'smg', tier: 3, barrel: 'pistol', mag: 2, stock: 2, rail: 1, grip: 1, bipod: 0, steel: 5, sheet: 3, spring: 1, extra: 1 },
  { id: 'tacz:uzi', name: 'uzi', ammo: 'tacz:9mm', cls: 'smg', tier: 2, barrel: 'pistol', mag: 2, stock: 1, rail: 0, grip: 1, bipod: 0, steel: 4, sheet: 2, spring: 1, extra: 1 },
  { id: 'tacz:vector45', name: 'vector45', ammo: 'tacz:45acp', cls: 'smg', tier: 3, barrel: 'pistol', mag: 2, stock: 1, rail: 2, grip: 1, bipod: 0, steel: 5, sheet: 3, spring: 1, extra: 1 },
]

var MZ_ATTS = [
  { id: 'tacz:ammo_mod_fmj', name: 'ammo_mod_fmj', cls: 'extended_mag', tier: 1 },
  { id: 'tacz:ammo_mod_he', name: 'ammo_mod_he', cls: 'extended_mag', tier: 1 },
  { id: 'tacz:ammo_mod_hp', name: 'ammo_mod_hp', cls: 'extended_mag', tier: 1 },
  { id: 'tacz:ammo_mod_i', name: 'ammo_mod_i', cls: 'extended_mag', tier: 1 },
  { id: 'tacz:ammo_mod_slug', name: 'ammo_mod_slug', cls: 'extended_mag', tier: 1 },
  { id: 'tacz:bayonet_6h3', name: 'bayonet_6h3', cls: 'muzzle', tier: 1 },
  { id: 'tacz:bayonet_m9', name: 'bayonet_m9', cls: 'muzzle', tier: 1 },
  { id: 'tacz:deagle_golden_long_barrel', name: 'deagle_golden_long_barrel', cls: 'muzzle', tier: 3 },
  { id: 'tacz:extended_mag_1', name: 'extended_mag_1', cls: 'extended_mag', tier: 3 },
  { id: 'tacz:extended_mag_2', name: 'extended_mag_2', cls: 'extended_mag', tier: 3 },
  { id: 'tacz:extended_mag_3', name: 'extended_mag_3', cls: 'extended_mag', tier: 3 },
  { id: 'tacz:grip_cobra', name: 'grip_cobra', cls: 'grip', tier: 1 },
  { id: 'tacz:grip_cqr', name: 'grip_cqr', cls: 'grip', tier: 1 },
  { id: 'tacz:grip_magpul_afg_2', name: 'grip_magpul_afg_2', cls: 'grip', tier: 1 },
  { id: 'tacz:grip_osovets_black', name: 'grip_osovets_black', cls: 'grip', tier: 1 },
  { id: 'tacz:grip_rk0', name: 'grip_rk0', cls: 'grip', tier: 1 },
  { id: 'tacz:grip_rk1_b25u', name: 'grip_rk1_b25u', cls: 'grip', tier: 1 },
  { id: 'tacz:grip_rk6', name: 'grip_rk6', cls: 'grip', tier: 1 },
  { id: 'tacz:grip_se_5', name: 'grip_se_5', cls: 'grip', tier: 1 },
  { id: 'tacz:grip_td', name: 'grip_td', cls: 'grip', tier: 1 },
  { id: 'tacz:grip_vertical_military', name: 'grip_vertical_military', cls: 'grip', tier: 1 },
  { id: 'tacz:grip_vertical_ranger', name: 'grip_vertical_ranger', cls: 'grip', tier: 1 },
  { id: 'tacz:grip_vertical_talon', name: 'grip_vertical_talon', cls: 'grip', tier: 1 },
  { id: 'tacz:laser_compact', name: 'laser_compact', cls: 'laser', tier: 2 },
  { id: 'tacz:laser_lopro', name: 'laser_lopro', cls: 'laser', tier: 2 },
  { id: 'tacz:laser_nightstick', name: 'laser_nightstick', cls: 'laser', tier: 2 },
  { id: 'tacz:laser_peq15', name: 'laser_peq15', cls: 'laser', tier: 2 },
  { id: 'tacz:laser_peq6', name: 'laser_peq6', cls: 'laser', tier: 2 },
  { id: 'tacz:light_extended_mag_1', name: 'light_extended_mag_1', cls: 'extended_mag', tier: 2 },
  { id: 'tacz:light_extended_mag_2', name: 'light_extended_mag_2', cls: 'extended_mag', tier: 2 },
  { id: 'tacz:light_extended_mag_3', name: 'light_extended_mag_3', cls: 'extended_mag', tier: 2 },
  { id: 'tacz:muzzle_brake_cthulhu', name: 'muzzle_brake_cthulhu', cls: 'muzzle', tier: 2 },
  { id: 'tacz:muzzle_brake_cyclone_d2', name: 'muzzle_brake_cyclone_d2', cls: 'muzzle', tier: 2 },
  { id: 'tacz:muzzle_brake_mastiff_sg', name: 'muzzle_brake_mastiff_sg', cls: 'muzzle', tier: 2 },
  { id: 'tacz:muzzle_brake_pioneer', name: 'muzzle_brake_pioneer', cls: 'muzzle', tier: 2 },
  { id: 'tacz:muzzle_brake_timeless50', name: 'muzzle_brake_timeless50', cls: 'muzzle', tier: 2 },
  { id: 'tacz:muzzle_brake_trex', name: 'muzzle_brake_trex', cls: 'muzzle', tier: 2 },
  { id: 'tacz:muzzle_choke_sg', name: 'muzzle_choke_sg', cls: 'muzzle', tier: 1 },
  { id: 'tacz:muzzle_compensator_trident', name: 'muzzle_compensator_trident', cls: 'muzzle', tier: 2 },
  { id: 'tacz:muzzle_silencer_knight_qd', name: 'muzzle_silencer_knight_qd', cls: 'muzzle', tier: 3 },
  { id: 'tacz:muzzle_silencer_mirage', name: 'muzzle_silencer_mirage', cls: 'muzzle', tier: 3 },
  { id: 'tacz:muzzle_silencer_phantom_s1', name: 'muzzle_silencer_phantom_s1', cls: 'muzzle', tier: 3 },
  { id: 'tacz:muzzle_silencer_ptilopsis', name: 'muzzle_silencer_ptilopsis', cls: 'muzzle', tier: 3 },
  { id: 'tacz:muzzle_silencer_sg', name: 'muzzle_silencer_sg', cls: 'muzzle', tier: 3 },
  { id: 'tacz:muzzle_silencer_ursus', name: 'muzzle_silencer_ursus', cls: 'muzzle', tier: 3 },
  { id: 'tacz:muzzle_silencer_vulture', name: 'muzzle_silencer_vulture', cls: 'muzzle', tier: 3 },
  { id: 'tacz:muzzle_silencer_wraith', name: 'muzzle_silencer_wraith', cls: 'muzzle', tier: 3 },
  { id: 'tacz:oem_stock_heavy', name: 'oem_stock_heavy', cls: 'stock', tier: 1 },
  { id: 'tacz:oem_stock_light', name: 'oem_stock_light', cls: 'stock', tier: 1 },
  { id: 'tacz:oem_stock_tactical', name: 'oem_stock_tactical', cls: 'stock', tier: 1 },
  { id: 'tacz:scope_1873_6x', name: 'scope_1873_6x', cls: 'scope', tier: 2 },
  { id: 'tacz:scope_98k', name: 'scope_98k', cls: 'scope', tier: 2 },
  { id: 'tacz:scope_acog_ta31', name: 'scope_acog_ta31', cls: 'scope', tier: 3 },
  { id: 'tacz:scope_aug_default', name: 'scope_aug_default', cls: 'scope', tier: 2 },
  { id: 'tacz:scope_contender', name: 'scope_contender', cls: 'scope', tier: 2 },
  { id: 'tacz:scope_elcan_4x', name: 'scope_elcan_4x', cls: 'scope', tier: 2 },
  { id: 'tacz:scope_hamr', name: 'scope_hamr', cls: 'scope', tier: 2 },
  { id: 'tacz:scope_lpvo_1_6', name: 'scope_lpvo_1_6', cls: 'scope', tier: 3 },
  { id: 'tacz:scope_mk5hd', name: 'scope_mk5hd', cls: 'scope', tier: 3 },
  { id: 'tacz:scope_qmk152', name: 'scope_qmk152', cls: 'scope', tier: 2 },
  { id: 'tacz:scope_retro_2x', name: 'scope_retro_2x', cls: 'scope', tier: 2 },
  { id: 'tacz:scope_standard_8x', name: 'scope_standard_8x', cls: 'scope', tier: 3 },
  { id: 'tacz:scope_vudu', name: 'scope_vudu', cls: 'scope', tier: 3 },
  { id: 'tacz:shotgun_extended_mag_1', name: 'shotgun_extended_mag_1', cls: 'extended_mag', tier: 3 },
  { id: 'tacz:shotgun_extended_mag_2', name: 'shotgun_extended_mag_2', cls: 'extended_mag', tier: 3 },
  { id: 'tacz:shotgun_extended_mag_3', name: 'shotgun_extended_mag_3', cls: 'extended_mag', tier: 3 },
  { id: 'tacz:sight_552', name: 'sight_552', cls: 'scope', tier: 1 },
  { id: 'tacz:sight_acro_pistol', name: 'sight_acro_pistol', cls: 'scope', tier: 1 },
  { id: 'tacz:sight_acro_rifle', name: 'sight_acro_rifle', cls: 'scope', tier: 1 },
  { id: 'tacz:sight_coyote', name: 'sight_coyote', cls: 'scope', tier: 1 },
  { id: 'tacz:sight_deltapoint_pistol', name: 'sight_deltapoint_pistol', cls: 'scope', tier: 1 },
  { id: 'tacz:sight_deltapoint_rifle', name: 'sight_deltapoint_rifle', cls: 'scope', tier: 1 },
  { id: 'tacz:sight_exp3', name: 'sight_exp3', cls: 'scope', tier: 1 },
  { id: 'tacz:sight_fastfire_pistol', name: 'sight_fastfire_pistol', cls: 'scope', tier: 1 },
  { id: 'tacz:sight_fastfire_rifle', name: 'sight_fastfire_rifle', cls: 'scope', tier: 1 },
  { id: 'tacz:sight_okp7', name: 'sight_okp7', cls: 'scope', tier: 1 },
  { id: 'tacz:sight_p90', name: 'sight_p90', cls: 'scope', tier: 1 },
  { id: 'tacz:sight_pk06_pistol', name: 'sight_pk06_pistol', cls: 'scope', tier: 1 },
  { id: 'tacz:sight_pk06_rifle', name: 'sight_pk06_rifle', cls: 'scope', tier: 1 },
  { id: 'tacz:sight_rmr_dot', name: 'sight_rmr_dot', cls: 'scope', tier: 1 },
  { id: 'tacz:sight_sro_dot', name: 'sight_sro_dot', cls: 'scope', tier: 1 },
  { id: 'tacz:sight_srs_02', name: 'sight_srs_02', cls: 'scope', tier: 1 },
  { id: 'tacz:sight_t1', name: 'sight_t1', cls: 'scope', tier: 1 },
  { id: 'tacz:sight_t2', name: 'sight_t2', cls: 'scope', tier: 1 },
  { id: 'tacz:sight_uh1', name: 'sight_uh1', cls: 'scope', tier: 1 },
  { id: 'tacz:sniper_extended_mag_1', name: 'sniper_extended_mag_1', cls: 'extended_mag', tier: 3 },
  { id: 'tacz:sniper_extended_mag_2', name: 'sniper_extended_mag_2', cls: 'extended_mag', tier: 3 },
  { id: 'tacz:sniper_extended_mag_3', name: 'sniper_extended_mag_3', cls: 'extended_mag', tier: 3 },
  { id: 'tacz:stock_ak12', name: 'stock_ak12', cls: 'stock', tier: 2 },
  { id: 'tacz:stock_carbon_bone_c5', name: 'stock_carbon_bone_c5', cls: 'stock', tier: 2 },
  { id: 'tacz:stock_heavy_spas_12', name: 'stock_heavy_spas_12', cls: 'stock', tier: 2 },
  { id: 'tacz:stock_hk_slim_line', name: 'stock_hk_slim_line', cls: 'stock', tier: 2 },
  { id: 'tacz:stock_m4ss', name: 'stock_m4ss', cls: 'stock', tier: 2 },
  { id: 'tacz:stock_militech_b5', name: 'stock_militech_b5', cls: 'stock', tier: 2 },
  { id: 'tacz:stock_moe', name: 'stock_moe', cls: 'stock', tier: 2 },
  { id: 'tacz:stock_ripstock', name: 'stock_ripstock', cls: 'stock', tier: 2 },
  { id: 'tacz:stock_sba3', name: 'stock_sba3', cls: 'stock', tier: 2 },
  { id: 'tacz:stock_tactical_ar', name: 'stock_tactical_ar', cls: 'stock', tier: 2 },
  { id: 'tacz:stock_tactical_spas_12', name: 'stock_tactical_spas_12', cls: 'stock', tier: 2 },
]

var MZ_MW = [
  { id: 'mianbaos_modernwarfare:agmmissile_1', name: 'agmmissile_1', zh: '空对地导弹（普通）', cat: 'missile', tier: 3 },
  { id: 'mianbaos_modernwarfare:agmmissile_2', name: 'agmmissile_2', zh: '空对地导弹（攻顶）', cat: 'missile', tier: 3 },
  { id: 'mianbaos_modernwarfare:agmmissile_3', name: 'agmmissile_3', zh: '空对地导弹（普通）', cat: 'missile', tier: 3 },
  { id: 'mianbaos_modernwarfare:agmmissile_4', name: 'agmmissile_4', zh: '空对地导弹（攻顶）', cat: 'missile', tier: 3 },
  { id: 'mianbaos_modernwarfare:aim_120', name: 'aim_120', zh: 'AIM-120中程空对空导弹', cat: 'missile', tier: 4 },
  { id: 'mianbaos_modernwarfare:antiradiationmissile', name: 'antiradiationmissile', zh: '反辐射导弹', cat: 'missile', tier: 4 },
  { id: 'mianbaos_modernwarfare:antitankmissile_1', name: 'antitankmissile_1', zh: '反坦克导弹（普通）', cat: 'missile', tier: 3 },
  { id: 'mianbaos_modernwarfare:antitankmissile_2', name: 'antitankmissile_2', zh: '反坦克导弹（攻顶）', cat: 'missile', tier: 3 },
  { id: 'mianbaos_modernwarfare:antitankmissilelauncherportable', name: 'antitankmissilelauncherportable', zh: '单兵反坦克导弹发射器', cat: 'missile', tier: 3 },
  { id: 'mianbaos_modernwarfare:ap_sammo', name: 'ap_sammo', zh: 'APS弹药', cat: 'mw_ammo', tier: 1 },
  { id: 'mianbaos_modernwarfare:bombdrone_spawn_egg', name: 'bombdrone_spawn_egg', zh: '爆爆无人机', cat: 'drone', tier: 2 },
  { id: 'mianbaos_modernwarfare:bombitem', name: 'bombitem', zh: '航空炸弹(物品）', cat: 'bomb', tier: 3 },
  { id: 'mianbaos_modernwarfare:bombjetitem', name: 'bombjetitem', zh: '炸弹小飞机', cat: 'bomb', tier: 3 },
  { id: 'mianbaos_modernwarfare:bunkerdrone_spawn_egg', name: 'bunkerdrone_spawn_egg', zh: '堡垒', cat: 'drone', tier: 2 },
  { id: 'mianbaos_modernwarfare:c4_item', name: 'c4_item', zh: 'C4炸药（定时）', cat: 'demolition', tier: 2 },
  { id: 'mianbaos_modernwarfare:c4_item_2', name: 'c4_item_2', zh: 'C4炸药（遥控）', cat: 'demolition', tier: 2 },
  { id: 'mianbaos_modernwarfare:c_4cutter', name: 'c_4cutter', zh: 'C4拆除钳', cat: 'demolition', tier: 2 },
  { id: 'mianbaos_modernwarfare:chennelchanger', name: 'chennelchanger', zh: '频道设置器', cat: 'device', tier: 2 },
  { id: 'mianbaos_modernwarfare:ciw_smissileitem', name: 'ciw_smissileitem', zh: '防空反导系统', cat: 'turret', tier: 4 },
  { id: 'mianbaos_modernwarfare:ciws_item', name: 'ciws_item', zh: '近防炮系统', cat: 'turret', tier: 5 },
  { id: 'mianbaos_modernwarfare:closemissile_1', name: 'closemissile_1', zh: '近距离空空格斗导弹', cat: 'missile', tier: 3 },
  { id: 'mianbaos_modernwarfare:closemissile_2', name: 'closemissile_2', zh: '近距离空空格斗导弹', cat: 'missile', tier: 3 },
  { id: 'mianbaos_modernwarfare:clusterbombitem', name: 'clusterbombitem', zh: '集束炸弹（物品）', cat: 'bomb', tier: 3 },
  { id: 'mianbaos_modernwarfare:clustergrenadeitem', name: 'clustergrenadeitem', zh: '集束手雷', cat: 'grenade', tier: 1 },
  { id: 'mianbaos_modernwarfare:coordinatechanger', name: 'coordinatechanger', zh: '坐标设置器', cat: 'device', tier: 2 },
  { id: 'mianbaos_modernwarfare:countermeasureammo', name: 'countermeasureammo', zh: '热诱弹弹药', cat: 'mw_ammo', tier: 1 },
  { id: 'mianbaos_modernwarfare:cruisemissileitem', name: 'cruisemissileitem', zh: '巡航导弹(物品）', cat: 'missile', tier: 4 },
  { id: 'mianbaos_modernwarfare:cruisemissilelowitem', name: 'cruisemissilelowitem', zh: '巡航导弹(物品）', cat: 'missile', tier: 4 },
  { id: 'mianbaos_modernwarfare:dianzuan', name: 'dianzuan', zh: '电钻', cat: 'device', tier: 2 },
  { id: 'mianbaos_modernwarfare:earthpenetratorbombitem', name: 'earthpenetratorbombitem', zh: '钻地弹（物品）', cat: 'bomb', tier: 3 },
  { id: 'mianbaos_modernwarfare:explode_grenade', name: 'explode_grenade', zh: '手雷', cat: 'grenade', tier: 1 },
  { id: 'mianbaos_modernwarfare:far_missile_1', name: 'far_missile_1', zh: '远距离空空导弹', cat: 'missile', tier: 3 },
  { id: 'mianbaos_modernwarfare:far_missile_2', name: 'far_missile_2', zh: '远距离空空导弹', cat: 'missile', tier: 3 },
  { id: 'mianbaos_modernwarfare:farrocketlaserguided', name: 'farrocketlaserguided', zh: '制导火箭弹', cat: 'rocket_ammo', tier: 2 },
  { id: 'mianbaos_modernwarfare:farrocketscluster', name: 'farrocketscluster', zh: '集束火箭弹', cat: 'rocket_ammo', tier: 2 },
  { id: 'mianbaos_modernwarfare:farrocketsexplosion', name: 'farrocketsexplosion', zh: '高爆破甲火箭弹', cat: 'rocket_ammo', tier: 2 },
  { id: 'mianbaos_modernwarfare:farrocketsfire', name: 'farrocketsfire', zh: '燃烧火箭弹', cat: 'rocket_ammo', tier: 2 },
  { id: 'mianbaos_modernwarfare:farrocketswp', name: 'farrocketswp', zh: '白磷火箭弹', cat: 'rocket_ammo', tier: 2 },
  { id: 'mianbaos_modernwarfare:fire_bombitem', name: 'fire_bombitem', zh: '凝固汽油炸弹(物品）', cat: 'bomb', tier: 3 },
  { id: 'mianbaos_modernwarfare:fireballdrone_spawn_egg', name: 'fireballdrone_spawn_egg', zh: '火球无人机', cat: 'drone', tier: 2 },
  { id: 'mianbaos_modernwarfare:firesupportcallergasmortar', name: 'firesupportcallergasmortar', zh: '火力支援呼叫器（毒气迫击炮）', cat: 'caller', tier: 2 },
  { id: 'mianbaos_modernwarfare:firesupportcallermortar', name: 'firesupportcallermortar', zh: '火力支援呼叫器（高爆迫击炮）', cat: 'caller', tier: 2 },
  { id: 'mianbaos_modernwarfare:firesupportcallersmokemortar', name: 'firesupportcallersmokemortar', zh: '火力支援呼叫器（烟雾迫击炮）', cat: 'caller', tier: 2 },
  { id: 'mianbaos_modernwarfare:firesurpportsmokegrenade', name: 'firesurpportsmokegrenade', zh: '火力打击指示烟雾弹', cat: 'grenade', tier: 1 },
  { id: 'mianbaos_modernwarfare:gasmask_helmet', name: 'gasmask_helmet', zh: '防毒面具', cat: 'gear', tier: 1 },
  { id: 'mianbaos_modernwarfare:glidebombitem', name: 'glidebombitem', zh: '滑翔炸弹（物品）', cat: 'special', tier: 3 },
  { id: 'mianbaos_modernwarfare:grenade_2', name: 'grenade_2', zh: '榴弹弹药', cat: 'mw_ammo', tier: 1 },
  { id: 'mianbaos_modernwarfare:groundmissile_1item', name: 'groundmissile_1item', zh: '陆基垂发高爆导弹（物品）', cat: 'missile', tier: 3 },
  { id: 'mianbaos_modernwarfare:groundmissile_2item', name: 'groundmissile_2item', zh: '陆基垂发集束导弹（物品）', cat: 'missile', tier: 3 },
  { id: 'mianbaos_modernwarfare:groundmissile_3item', name: 'groundmissile_3item', zh: '陆基垂发巡航导弹（物品）', cat: 'missile', tier: 4 },
  { id: 'mianbaos_modernwarfare:groundmissile_4item', name: 'groundmissile_4item', zh: '陆基垂发巡航导弹（物品）', cat: 'missile', tier: 4 },
  { id: 'mianbaos_modernwarfare:groundnuclearcruisemissileitem', name: 'groundnuclearcruisemissileitem', zh: '§b陆基垂发巡航核导弹（物品）', cat: 'nuke', tier: 5 },
  { id: 'mianbaos_modernwarfare:gun_turretitem', name: 'gun_turretitem', zh: '机枪自动炮塔', cat: 'turret', tier: 4 },
  { id: 'mianbaos_modernwarfare:gundefendercaritem', name: 'gundefendercaritem', zh: '机枪无人车', cat: 'drone', tier: 2 },
  { id: 'mianbaos_modernwarfare:hatchkey', name: 'hatchkey', zh: '舱盖钥匙', cat: 'device', tier: 2 },
  { id: 'mianbaos_modernwarfare:highexplosiveguidedtorpedoitem', name: 'highexplosiveguidedtorpedoitem', zh: '高爆制导鱼雷（物品）', cat: 'torpedo', tier: 4 },
  { id: 'mianbaos_modernwarfare:highexplosivetorpedoitem', name: 'highexplosivetorpedoitem', zh: '高爆鱼雷（物品）', cat: 'torpedo', tier: 4 },
  { id: 'mianbaos_modernwarfare:highexplosivevisualguidedtorpedoitem', name: 'highexplosivevisualguidedtorpedoitem', zh: '高爆视觉制导鱼雷（物品）', cat: 'torpedo', tier: 4 },
  { id: 'mianbaos_modernwarfare:highresistancebomb', name: 'highresistancebomb', zh: '高阻炸弹（物品）', cat: 'bomb', tier: 3 },
  { id: 'mianbaos_modernwarfare:hornetdrone_spawn_egg', name: 'hornetdrone_spawn_egg', zh: '马蜂无人机', cat: 'drone', tier: 2 },
  { id: 'mianbaos_modernwarfare:jdam_1', name: 'jdam_1', zh: '激光制导炸弹（物品）', cat: 'bomb', tier: 3 },
  { id: 'mianbaos_modernwarfare:jdam_2', name: 'jdam_2', zh: '复合制导炸弹（物品）', cat: 'bomb', tier: 3 },
  { id: 'mianbaos_modernwarfare:laser_guided_missile', name: 'laser_guided_missile', zh: '激光制导导弹', cat: 'missile', tier: 3 },
  { id: 'mianbaos_modernwarfare:laserguidedmissilesecond', name: 'laserguidedmissilesecond', zh: '激光制导导弹', cat: 'missile', tier: 3 },
  { id: 'mianbaos_modernwarfare:lasermissilelauncheritem', name: 'lasermissilelauncheritem', zh: '激光制导导弹固定发射器', cat: 'turret', tier: 4 },
  { id: 'mianbaos_modernwarfare:laserpointer', name: 'laserpointer', zh: '激光指示器', cat: 'device', tier: 2 },
  { id: 'mianbaos_modernwarfare:laserturretitem', name: 'laserturretitem', zh: '激光防御炮塔', cat: 'turret', tier: 4 },
  { id: 'mianbaos_modernwarfare:littlebombitem', name: 'littlebombitem', zh: '小型炸弹（物品）', cat: 'bomb', tier: 3 },
  { id: 'mianbaos_modernwarfare:magicalstick', name: 'magicalstick', zh: '§5神奇的棍子', cat: 'special', tier: 7 },
  { id: 'mianbaos_modernwarfare:medicalkits', name: 'medicalkits', zh: '医疗箱（道具）', cat: 'medical', tier: 1 },
  { id: 'mianbaos_modernwarfare:medicalpack', name: 'medicalpack', zh: '急救包', cat: 'medical', tier: 1 },
  { id: 'mianbaos_modernwarfare:medium_ai_mmissile_2', name: 'medium_ai_mmissile_2', zh: '中距离空空导弹', cat: 'missile', tier: 3 },
  { id: 'mianbaos_modernwarfare:medium_bombitem', name: 'medium_bombitem', zh: '中型航空炸弹(物品）', cat: 'bomb', tier: 3 },
  { id: 'mianbaos_modernwarfare:medium_missile', name: 'medium_missile', zh: '中距离空空导弹', cat: 'missile', tier: 3 },
  { id: 'mianbaos_modernwarfare:mica_em', name: 'mica_em', zh: 'MICA-EM中程空对空导弹', cat: 'missile', tier: 4 },
  { id: 'mianbaos_modernwarfare:missile_turretitem', name: 'missile_turretitem', zh: '导弹防卫炮塔', cat: 'turret', tier: 4 },
  { id: 'mianbaos_modernwarfare:mortar_wp_ammo', name: 'mortar_wp_ammo', zh: '迫击炮炮弹（白磷）', cat: 'mortar', tier: 2 },
  { id: 'mianbaos_modernwarfare:mortarairburstammo', name: 'mortarairburstammo', zh: '迫击炮炮弹（空爆）', cat: 'mortar', tier: 2 },
  { id: 'mianbaos_modernwarfare:mortarammo', name: 'mortarammo', zh: '迫击炮炮弹', cat: 'mortar', tier: 2 },
  { id: 'mianbaos_modernwarfare:mortarfireammo', name: 'mortarfireammo', zh: '迫击炮炮弹（燃烧）', cat: 'mortar', tier: 2 },
  { id: 'mianbaos_modernwarfare:mortargasammo', name: 'mortargasammo', zh: '迫击炮炮弹（毒气）', cat: 'mortar', tier: 2 },
  { id: 'mianbaos_modernwarfare:mortarlaserguidedammo', name: 'mortarlaserguidedammo', zh: '迫击炮炮弹（激光制导）', cat: 'mortar', tier: 2 },
  { id: 'mianbaos_modernwarfare:mortarsmokeammo', name: 'mortarsmokeammo', zh: '迫击炮炮弹（烟雾）', cat: 'mortar', tier: 2 },
  { id: 'mianbaos_modernwarfare:nightvisiondevice_helmet', name: 'nightvisiondevice_helmet', zh: '§a夜视仪', cat: 'gear', tier: 3 },
  { id: 'mianbaos_modernwarfare:nuclearbombitem', name: 'nuclearbombitem', zh: '§b核炸弹(物品)', cat: 'nuke', tier: 5 },
  { id: 'mianbaos_modernwarfare:nuclearcruisemissileitem', name: 'nuclearcruisemissileitem', zh: '§b巡航核导弹(物品)', cat: 'nuke', tier: 5 },
  { id: 'mianbaos_modernwarfare:opticalguidedmissile', name: 'opticalguidedmissile', zh: '光学制导导弹', cat: 'missile', tier: 4 },
  { id: 'mianbaos_modernwarfare:pilothelmet_helmet', name: 'pilothelmet_helmet', zh: '飞行员头盔', cat: 'gear', tier: 1 },
  { id: 'mianbaos_modernwarfare:portable_saclo_smissilelauncher', name: 'portable_saclo_smissilelauncher', zh: '单兵半自动指令线反坦克筒', cat: 'special', tier: 3 },
  { id: 'mianbaos_modernwarfare:portableantiairmissile', name: 'portableantiairmissile', zh: '防空导弹', cat: 'mw_ammo', tier: 1 },
  { id: 'mianbaos_modernwarfare:portableantiairmissile_2', name: 'portableantiairmissile_2', zh: '高速防空导弹', cat: 'mw_ammo', tier: 1 },
  { id: 'mianbaos_modernwarfare:portableantiairmissilelauncher', name: 'portableantiairmissilelauncher', zh: '单兵防空导弹发射器', cat: 'launcher', tier: 3 },
  { id: 'mianbaos_modernwarfare:portableantimissilemissile', name: 'portableantimissilemissile', zh: '反导导弹', cat: 'mw_ammo', tier: 1 },
  { id: 'mianbaos_modernwarfare:portableantitankrocket', name: 'portableantitankrocket', zh: '反坦克火箭弹(破甲弹头)', cat: 'mw_ammo', tier: 1 },
  { id: 'mianbaos_modernwarfare:portableantitankrocket_2', name: 'portableantitankrocket_2', zh: '反坦克火箭弹(高爆弹头)', cat: 'mw_ammo', tier: 1 },
  { id: 'mianbaos_modernwarfare:portableantitankrocketlauncher', name: 'portableantitankrocketlauncher', zh: '反坦克火箭筒', cat: 'launcher', tier: 3 },
  { id: 'mianbaos_modernwarfare:portableflamelauncher', name: 'portableflamelauncher', zh: '单兵喷火器', cat: 'launcher', tier: 3 },
  { id: 'mianbaos_modernwarfare:portableflamelauncherpack_chestplate', name: 'portableflamelauncherpack_chestplate', zh: '单兵喷火器背包', cat: 'gear', tier: 1 },
  { id: 'mianbaos_modernwarfare:radarconnector', name: 'radarconnector', zh: '远程雷达控制器', cat: 'device', tier: 3 },
  { id: 'mianbaos_modernwarfare:ravendrone_spawn_egg', name: 'ravendrone_spawn_egg', zh: '渡鸦', cat: 'drone', tier: 2 },
  { id: 'mianbaos_modernwarfare:remote_weapon_station_controller', name: 'remote_weapon_station_controller', zh: '武器站遥控器', cat: 'device', tier: 3 },
  { id: 'mianbaos_modernwarfare:rocket_turretitem', name: 'rocket_turretitem', zh: '火箭弹支援炮塔', cat: 'turret', tier: 4 },
  { id: 'mianbaos_modernwarfare:rocketer_spawn_egg', name: 'rocketer_spawn_egg', zh: '火箭手无人机', cat: 'drone', tier: 2 },
  { id: 'mianbaos_modernwarfare:rockets', name: 'rockets', zh: '火箭弹', cat: 'rocket_ammo', tier: 2 },
  { id: 'mianbaos_modernwarfare:smasherdrone_spawn_egg', name: 'smasherdrone_spawn_egg', zh: '粉碎者无人机', cat: 'drone', tier: 2 },
  { id: 'mianbaos_modernwarfare:smokegrenade', name: 'smokegrenade', zh: '烟雾手雷', cat: 'grenade', tier: 1 },
  { id: 'mianbaos_modernwarfare:smokelauncherammo', name: 'smokelauncherammo', zh: '烟雾弹弹药', cat: 'mw_ammo', tier: 1 },
  { id: 'mianbaos_modernwarfare:snitchdrone_spawn_egg', name: 'snitchdrone_spawn_egg', zh: '告密者无人机', cat: 'drone', tier: 2 },
  { id: 'mianbaos_modernwarfare:speedupstick', name: 'speedupstick', zh: '§5加速魔法棒~~~', cat: 'special', tier: 7 },
  { id: 'mianbaos_modernwarfare:targetpointer', name: 'targetpointer', zh: '目标指示器', cat: 'device', tier: 2 },
  { id: 'mianbaos_modernwarfare:terminalconector', name: 'terminalconector', zh: '终端连接器', cat: 'device', tier: 2 },
  { id: 'mianbaos_modernwarfare:terminalsaver', name: 'terminalsaver', zh: '终端数据储存器', cat: 'device', tier: 3 },
  { id: 'mianbaos_modernwarfare:tn_tdetonater', name: 'tn_tdetonater', zh: '炸药 C4起爆器', cat: 'demolition', tier: 2 },
  { id: 'mianbaos_modernwarfare:uavcall', name: 'uavcall', zh: '侦察无人机呼叫器', cat: 'drone', tier: 2 },
  { id: 'mianbaos_modernwarfare:ucavitem', name: 'ucavitem', zh: '弹簧刀无人机', cat: 'drone', tier: 2 },
  { id: 'mianbaos_modernwarfare:waspdrone_spawn_egg', name: 'waspdrone_spawn_egg', zh: '黄蜂无人机', cat: 'drone', tier: 2 },
  { id: 'mianbaos_modernwarfare:whitephosphorusbombitem', name: 'whitephosphorusbombitem', zh: '白磷弹炸弹（物品）', cat: 'bomb', tier: 3 },
  { id: 'mianbaos_modernwarfare:wolvesgrenade', name: 'wolvesgrenade', zh: '狼群手雷', cat: 'grenade', tier: 1 },
]
