// ============================================================================
//  本文件由 kubejs/_recon/gen_js.py 自动生成 —— 中间物品注册（启动脚本）。
//  共享零件 + 每把枪的机匣半成品 + 每个口径的弹壳。
// ============================================================================

StartupEvents.registry('item', event => {
  // ---- 共享材料与零件 ----
  event.create('gun_steel_ingot').texture('tfmg:item/steel_ingot')
  event.create('gun_steel_sheet').texture('tfmg:item/cast_iron_sheet')
  event.create('spring_steel_ingot').texture('tfmg:item/steel_ingot')
  event.create('spring_steel_sheet').texture('tfmg:item/cast_iron_sheet')
  event.create('spring_wire').texture('tfmg:item/aluminum_wire')
  event.create('recoil_spring').texture('tfmg:item/screw')
  event.create('barrel_blank').texture('tfmg:item/steel_ingot')
  event.create('incomplete_barrel', 'create:sequenced_assembly').texture('tfmg:item/steel_ingot')
  event.create('rifled_barrel').texture('tfmg:item/steel_ingot')
  event.create('barrel_pistol').texture('tfmg:item/steel_ingot')
  event.create('barrel_rifle').texture('tfmg:item/steel_ingot')
  event.create('barrel_heavy').texture('tfmg:item/steel_ingot')
  event.create('barrel_shotgun').texture('tfmg:item/steel_ingot')
  event.create('launcher_tube').texture('tfmg:item/steel_ingot')
  event.create('receiver_forging').texture('create:item/iron_sheet')
  event.create('incomplete_receiver', 'create:sequenced_assembly').texture('create:item/iron_sheet')
  event.create('receiver_machined').texture('create:item/iron_sheet')
  event.create('bolt_group').texture('create:item/precision_mechanism')
  event.create('firing_pin').texture('tfmg:item/screw')
  event.create('trigger_group').texture('create:item/cogwheel')
  event.create('magazine_body').texture('create:item/brass_sheet')
  event.create('rail_mount').texture('create:item/iron_sheet')
  event.create('bipod').texture('tfmg:item/screw')
  event.create('polymer_furniture').texture('tfmg:item/plastic_sheet')
  event.create('carbon_furniture').texture('tfmg:item/plastic_sheet')
  event.create('aluminum_receiver').texture('tfmg:item/aluminum_sheet')
  event.create('brass_blank').texture('create:item/brass_sheet')
  event.create('brass_cup').texture('create:item/brass_sheet')
  event.create('steel_blank').texture('tfmg:item/cast_iron_sheet')
  event.create('steel_cup').texture('tfmg:item/cast_iron_sheet')
  event.create('brass_cup_bright').texture('create:item/brass_sheet')
  event.create('steel_cup_bright').texture('tfmg:item/cast_iron_sheet')
  event.create('primer_cup').texture('create:item/copper_sheet')
  event.create('priming_compound').texture('createbigcannons:item/packed_gunpowder')
  event.create('primer_small').texture('create:item/copper_sheet')
  event.create('primer_large').texture('create:item/copper_sheet')
  event.create('primer_shotgun').texture('create:item/copper_sheet')
  event.create('smokeless_powder').texture('createbigcannons:item/packed_gunpowder')
  event.create('black_powder').texture('createbigcannons:item/packed_gunpowder')
  event.create('lead_core').texture('tfmg:item/lead_sheet')
  event.create('tungsten_core').texture('chemica:item/tungsten_ingot')
  event.create('proj_pistol').texture('tfmg:item/lead_sheet')
  event.create('proj_mag').texture('tfmg:item/lead_sheet')
  event.create('proj_mag_heavy').texture('tfmg:item/lead_sheet')
  event.create('proj_ap_small').texture('chemica:item/tungsten_ingot')
  event.create('proj_rifle').texture('tfmg:item/lead_sheet')
  event.create('proj_rifle_heavy').texture('tfmg:item/lead_sheet')
  event.create('proj_sniper').texture('tfmg:item/lead_sheet')
  event.create('proj_heavy_ap').texture('chemica:item/tungsten_ingot')
  event.create('proj_heavy_lead').texture('tfmg:item/lead_sheet')
  event.create('proj_shot').texture('tfmg:item/lead_sheet')
  event.create('proj_grenade40').texture('create:item/iron_sheet')
  event.create('proj_rocket').texture('create:item/iron_sheet')
  event.create('shot_hull').texture('tfmg:item/plastic_sheet')
  event.create('explosive_filler').texture('createbigcannons:item/packed_gunpowder')
  event.create('shaped_charge').texture('create:item/copper_sheet')
  event.create('bomb_casing').texture('create:item/iron_sheet')
  event.create('bomb_casing_filled').texture('create:item/iron_sheet')
  event.create('warhead_small').texture('create:item/iron_sheet')
  event.create('warhead_medium').texture('create:item/iron_sheet')
  event.create('warhead_heavy').texture('create:item/iron_sheet')
  event.create('rocket_motor').texture('create:item/iron_sheet')
  event.create('guidance_module').texture('northstar:item/circuit')
  event.create('seeker_head').texture('create_optical:item/mirror')
  event.create('fuze').texture('powergrid:item/circuit_board')
  event.create('tnt_filler').texture('createbigcannons:item/packed_gunpowder')
  event.create('drone_frame').texture('tfmg:item/aluminum_sheet')
  event.create('drone_motor').texture('tfmg:item/screw')
  event.create('optic_lens').texture('create_optical:item/mirror')
  event.create('optic_tube').texture('tfmg:item/aluminum_sheet')
  event.create('suppressor_baffle').texture('tfmg:item/heavy_plate')
  event.create('magnetic_sensor').texture('powergrid:item/circuit_board')
  event.create('pressure_plate_kit').texture('tfmg:item/heavy_plate')
  event.create('gauze').texture('minecraft:item/paper')
  event.create('antiseptic').texture('minecraft:item/potion')
  event.create('splint').texture('minecraft:item/stick')
  event.create('ballistic_plate').texture('tfmg:item/heavy_plate')
  event.create('composite_plate').texture('chemica:item/carbon_fiber_composite_sheet')
  event.create('filter_canister').texture('create:item/iron_sheet')
  event.create('nv_tube').texture('northstar:item/circuit')

  // ---- 每把枪的机匣组半成品 ----
  event.create('incomplete_aa12', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_ai_awp', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_ak47', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_aug', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_b93r', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_cz75', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_db_long', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_db_short', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_deagle', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_deagle_golden', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_fn_evolys', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_fn_fal', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_g36k', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_glock_17', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_hk416d', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_hk_g3', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_hk_mk23', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_hk_mp5a5', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_kar98', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_lonetrail', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_m1014', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_m107', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_m16a1', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_m16a4', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_m1911', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_m249', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_m320', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_m4a1', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_m700', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_m870', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_m95', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_m9a4', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_minigun', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_mk14', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_p320', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_p90', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_qbz_191', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_qbz_95', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_rhino357', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_rpg7', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_rpk', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_scar_h', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_scar_l', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_sks_tactical', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_spas_12', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_spr15hb', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_springfield1873', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_taurus500', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_taurus943', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_timeless50', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_type_81', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_ump45', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_uzi', 'create:sequenced_assembly').texture('create:item/precision_mechanism')
  event.create('incomplete_vector45', 'create:sequenced_assembly').texture('create:item/precision_mechanism')

  // ---- 每个口径的弹壳/弹壳坯 ----
  event.create('case_12g').texture('tfmg:item/plastic_sheet')
  event.create('case_22wmr').texture('create:item/brass_sheet')
  event.create('case_308').texture('create:item/brass_sheet')
  event.create('case_30_06').texture('create:item/brass_sheet')
  event.create('case_338').texture('create:item/brass_sheet')
  event.create('case_357mag').texture('create:item/brass_sheet')
  event.create('case_40mm').texture('tfmg:item/cast_iron_sheet')
  event.create('case_45_70').texture('create:item/brass_sheet')
  event.create('case_45acp').texture('create:item/brass_sheet')
  event.create('case_46x30').texture('create:item/brass_sheet')
  event.create('case_500mag').texture('create:item/brass_sheet')
  event.create('case_50ae').texture('create:item/brass_sheet')
  event.create('case_50bmg').texture('create:item/brass_sheet')
  event.create('case_545x39').texture('tfmg:item/cast_iron_sheet')
  event.create('case_556x45').texture('create:item/brass_sheet')
  event.create('case_57x28').texture('create:item/brass_sheet')
  event.create('case_58x42').texture('tfmg:item/cast_iron_sheet')
  event.create('case_68x51fury').texture('create:item/brass_sheet')
  event.create('case_762x25').texture('tfmg:item/cast_iron_sheet')
  event.create('case_762x39').texture('tfmg:item/cast_iron_sheet')
  event.create('case_762x54').texture('tfmg:item/cast_iron_sheet')
  event.create('case_792x57').texture('create:item/brass_sheet')
  event.create('case_9mm').texture('create:item/brass_sheet')
})
