// minecraft/kubejs/server_scripts/tacz_attachment_desc_last.js
// 由 .team/drafts/art-copy/15-生成配件描述.py 自动生成，请勿手改；改动请改 14-配件描述-94条.json 后重跑。
// 作用：B 方案的最高优先级层。ServerEvents.generateData('last') 的 virtual pack 被 KubeJS 追加在服务端 data 包列表末尾，
//       因此这 94 个 tacz:index/attachments/<id>.json 覆盖项优先级高于枪包内同名文件（枪包经 GunPackLoader 作为普通 data pack 注入）。
// 与静态层的关系：minecraft/kubejs/data/tacz/index/attachments/ 下另有一份逐字节相同的 94 个文件（人可复核 + 兜底）。
//       本开关只关掉脚本层；要完全关闭 B 方案，需同时清空静态目录（见核对表「回滚」）。
// 与 A 路径互斥：客户端脚本 tacz_attachment_tooltips.js 若同时开启，desc 行会重复一次。

// 本开关：true = 生成覆盖（默认）；false = 本脚本不产出任何文件
const TACZ_ATT_DESC_B = true;

if (TACZ_ATT_DESC_B) {
  ServerEvents.generateData('last', event => {
    event.text('tacz:index/attachments/bayonet_6h3.json', '{"name":"tacz.attachment.bayonet_6h3.name","display":"tacz:bayonet_6h3_display","data":"tacz:bayonet_6h3_data","tooltip":"tacz.attachment.bayonet_6h3.desc","type":"muzzle"}');
    event.text('tacz:index/attachments/bayonet_m9.json', '{"name":"tacz.attachment.bayonet_m9.name","display":"tacz:bayonet_m9_display","data":"tacz:bayonet_m9_data","tooltip":"tacz.attachment.bayonet_m9.desc","type":"muzzle"}');
    event.text('tacz:index/attachments/deagle_golden_long_barrel.json', '{"name":"tacz.attachment.deagle_golden_long_barrel.name","display":"tacz:deagle_golden_long_barrel_display","data":"tacz:deagle_golden_long_barrel_data","tooltip":"tacz.attachment.deagle_golden_long_barrel.desc","type":"muzzle"}');
    event.text('tacz:index/attachments/extended_mag_1.json', '{"name":"tacz.attachment.extended_mag_1.name","display":"tacz:extended_mag_1_display","data":"tacz:extended_mag_1_data","tooltip":"tacz.attachment.extended_mag_1.desc","type":"extended_mag","sort":1}');
    event.text('tacz:index/attachments/extended_mag_2.json', '{"name":"tacz.attachment.extended_mag_2.name","display":"tacz:extended_mag_2_display","data":"tacz:extended_mag_2_data","tooltip":"tacz.attachment.extended_mag_2.desc","type":"extended_mag","sort":2}');
    event.text('tacz:index/attachments/extended_mag_3.json', '{"name":"tacz.attachment.extended_mag_3.name","display":"tacz:extended_mag_3_display","data":"tacz:extended_mag_3_data","tooltip":"tacz.attachment.extended_mag_3.desc","type":"extended_mag","sort":3}');
    event.text('tacz:index/attachments/grip_cobra.json', '{"name":"tacz.attachment.grip_cobra.name","display":"tacz:grip_cobra_display","data":"tacz:grip_cobra_data","tooltip":"tacz.attachment.grip_cobra.desc","type":"grip","sort":1}');
    event.text('tacz:index/attachments/grip_cqr.json', '{"name":"tacz.attachment.grip_cqr","display":"tacz:grip_cqr_display","data":"tacz:grip_cqr_data","tooltip":"tacz.attachment.grip_cqr.desc","type":"grip","hidden":true}');
    event.text('tacz:index/attachments/grip_magpul_afg_2.json', '{"name":"tacz.attachment.grip_magpul_afg_2.name","display":"tacz:grip_magpul_afg_2_display","data":"tacz:grip_magpul_afg_2_data","tooltip":"tacz.attachment.grip_magpul_afg_2.desc","type":"grip","sort":1}');
    event.text('tacz:index/attachments/grip_osovets_black.json', '{"name":"tacz.attachment.grip_osovets_black.name","display":"tacz:grip_osovets_black_display","data":"tacz:grip_osovets_black_data","tooltip":"tacz.attachment.grip_osovets_black.desc","type":"grip","sort":10}');
    event.text('tacz:index/attachments/grip_rk0.json', '{"name":"tacz.attachment.grip_rk0.name","display":"tacz:grip_rk0_display","data":"tacz:grip_rk0_data","tooltip":"tacz.attachment.grip_rk0.desc","type":"grip","sort":10}');
    event.text('tacz:index/attachments/grip_rk1_b25u.json', '{"name":"tacz.attachment.grip_rk1_b25u.name","display":"tacz:grip_rk1_b25u_display","data":"tacz:grip_rk1_b25u_data","tooltip":"tacz.attachment.grip_rk1_b25u.desc","type":"grip","sort":10}');
    event.text('tacz:index/attachments/grip_rk6.json', '{"name":"tacz.attachment.grip_rk6.name","display":"tacz:grip_rk6_display","data":"tacz:grip_rk6_data","tooltip":"tacz.attachment.grip_rk6.desc","type":"grip","sort":1}');
    event.text('tacz:index/attachments/grip_se_5.json', '{"name":"tacz.attachment.grip_se_5","display":"tacz:grip_se_5_display","data":"tacz:grip_se_5_data","tooltip":"tacz.attachment.grip_se_5.desc","type":"grip","sort":10}');
    event.text('tacz:index/attachments/grip_td.json', '{"name":"tacz.attachment.grip_td","display":"tacz:grip_td_display","data":"tacz:grip_td_data","tooltip":"tacz.attachment.grip_td.desc","type":"grip","sort":10}');
    event.text('tacz:index/attachments/grip_vertical_military.json', '{"name":"tacz.attachment.grip_vertical_military.name","display":"tacz:grip_vertical_military_display","data":"tacz:grip_vertical_military_data","tooltip":"tacz.attachment.grip_vertical_military.desc","type":"grip","sort":10}');
    event.text('tacz:index/attachments/grip_vertical_ranger.json', '{"name":"tacz.attachment.grip_vertical_ranger.name","display":"tacz:grip_vertical_ranger_display","data":"tacz:grip_vertical_ranger_data","tooltip":"tacz.attachment.grip_vertical_ranger.desc","type":"grip","sort":10}');
    event.text('tacz:index/attachments/grip_vertical_talon.json', '{"name":"tacz.attachment.grip_vertical_talon.name","display":"tacz:grip_vertical_talon_display","data":"tacz:grip_vertical_talon_data","tooltip":"tacz.attachment.grip_vertical_talon.desc","type":"grip","sort":10}');
    event.text('tacz:index/attachments/laser_compact.json', '{"name":"tacz.attachment.laser_compact","display":"tacz:laser_compact_display","data":"tacz:laser_compact_data","tooltip":"tacz.attachment.laser_compact.desc","type":"laser","sort":10}');
    event.text('tacz:index/attachments/laser_lopro.json', '{"name":"tacz.attachment.laser_lopro","display":"tacz:laser_lopro_display","data":"tacz:laser_lopro_data","tooltip":"tacz.attachment.laser_lopro.desc","type":"laser","sort":10}');
    event.text('tacz:index/attachments/laser_nightstick.json', '{"name":"tacz.attachment.laser_nightstick","display":"tacz:laser_nightstick_display","data":"tacz:laser_nightstick_data","tooltip":"tacz.attachment.laser_nightstick.desc","type":"laser","sort":10}');
    event.text('tacz:index/attachments/laser_peq15.json', '{"name":"tacz.attachment.laser_peq15","display":"tacz:laser_peq15_display","data":"tacz:laser_peq15_data","tooltip":"tacz.attachment.laser_peq15.desc","type":"laser","sort":10,"hidden":true}');
    event.text('tacz:index/attachments/laser_peq6.json', '{"name":"tacz.attachment.laser_peq6","display":"tacz:laser_peq6_display","data":"tacz:laser_peq6_data","tooltip":"tacz.attachment.laser_peq6.desc","type":"laser","sort":10}');
    event.text('tacz:index/attachments/light_extended_mag_1.json', '{"name":"tacz.attachment.light_extended_mag_1.name","display":"tacz:light_extended_mag_1_display","data":"tacz:light_extended_mag_1_data","tooltip":"tacz.attachment.light_extended_mag_1.desc","type":"extended_mag","sort":5}');
    event.text('tacz:index/attachments/light_extended_mag_2.json', '{"name":"tacz.attachment.light_extended_mag_2.name","display":"tacz:light_extended_mag_2_display","data":"tacz:light_extended_mag_2_data","tooltip":"tacz.attachment.light_extended_mag_2.desc","type":"extended_mag","sort":5}');
    event.text('tacz:index/attachments/light_extended_mag_3.json', '{"name":"tacz.attachment.light_extended_mag_3.name","display":"tacz:light_extended_mag_3_display","data":"tacz:light_extended_mag_3_data","tooltip":"tacz.attachment.light_extended_mag_3.desc","type":"extended_mag","sort":5}');
    event.text('tacz:index/attachments/muzzle_brake_cthulhu.json', '{"name":"tacz.attachment.muzzle_brake_cthulhu.name","display":"tacz:muzzle_brake_cthulhu_display","data":"tacz:muzzle_brake_cthulhu_data","tooltip":"tacz.attachment.muzzle_brake_cthulhu.desc","type":"muzzle"}');
    event.text('tacz:index/attachments/muzzle_brake_cyclone_d2.json', '{"name":"tacz.attachment.muzzle_brake_cyclone_d2.name","display":"tacz:muzzle_brake_cyclone_d2_display","data":"tacz:muzzle_brake_cyclone_d2_data","tooltip":"tacz.attachment.muzzle_brake_cyclone_d2.desc","type":"muzzle"}');
    event.text('tacz:index/attachments/muzzle_brake_mastiff_sg.json', '{"name":"tacz.attachment.muzzle_brake_mastiff_sg.name","display":"tacz:muzzle_brake_mastiff_sg_display","data":"tacz:muzzle_brake_mastiff_sg_data","tooltip":"tacz.attachment.muzzle_brake_mastiff_sg.desc","type":"muzzle"}');
    event.text('tacz:index/attachments/muzzle_brake_pioneer.json', '{"name":"tacz.attachment.muzzle_brake_pioneer.name","display":"tacz:muzzle_brake_pioneer_display","data":"tacz:muzzle_brake_pioneer_data","tooltip":"tacz.attachment.muzzle_brake_pioneer.desc","type":"muzzle"}');
    event.text('tacz:index/attachments/muzzle_brake_timeless50.json', '{"name":"tacz.attachment.muzzle_brake_timeless50.name","display":"tacz:muzzle_brake_timeless50_display","data":"tacz:muzzle_brake_timeless50_data","tooltip":"tacz.attachment.muzzle_brake_timeless50.desc","type":"muzzle"}');
    event.text('tacz:index/attachments/muzzle_brake_trex.json', '{"name":"tacz.attachment.muzzle_brake_trex.name","display":"tacz:muzzle_brake_trex_display","data":"tacz:muzzle_brake_trex_data","tooltip":"tacz.attachment.muzzle_brake_trex.desc","type":"muzzle"}');
    event.text('tacz:index/attachments/muzzle_choke_sg.json', '{"name":"tacz.attachment.muzzle_choke_sg.name","display":"tacz:muzzle_choke_sg_display","data":"tacz:muzzle_choke_sg_data","tooltip":"tacz.attachment.muzzle_choke_sg.desc","type":"muzzle"}');
    event.text('tacz:index/attachments/muzzle_compensator_trident.json', '{"name":"tacz.attachment.muzzle_compensator_trident.name","display":"tacz:muzzle_compensator_trident_display","data":"tacz:muzzle_compensator_trident_data","tooltip":"tacz.attachment.muzzle_compensator_trident.desc","type":"muzzle"}');
    event.text('tacz:index/attachments/muzzle_silencer_knight_qd.json', '{"name":"tacz.attachment.muzzle_silencer_knight_qd.name","display":"tacz:muzzle_silencer_knight_qd_display","data":"tacz:muzzle_silencer_knight_qd_data","tooltip":"tacz.attachment.muzzle_silencer_knight_qd.desc","type":"muzzle"}');
    event.text('tacz:index/attachments/muzzle_silencer_mirage.json', '{"name":"tacz.attachment.muzzle_silencer_mirage.name","display":"tacz:muzzle_silencer_mirage_display","data":"tacz:muzzle_silencer_mirage_data","tooltip":"tacz.attachment.muzzle_silencer_mirage.desc","type":"muzzle"}');
    event.text('tacz:index/attachments/muzzle_silencer_phantom_s1.json', '{"name":"tacz.attachment.muzzle_silencer_phantom_s1.name","display":"tacz:muzzle_silencer_phantom_s1_display","data":"tacz:muzzle_silencer_phantom_s1_data","tooltip":"tacz.attachment.muzzle_silencer_phantom_s1.desc","type":"muzzle"}');
    event.text('tacz:index/attachments/muzzle_silencer_ptilopsis.json', '{"name":"tacz.attachment.muzzle_silencer_ptilopsis.name","display":"tacz:muzzle_silencer_ptilopsis_display","data":"tacz:muzzle_silencer_ptilopsis_data","tooltip":"tacz.attachment.muzzle_silencer_ptilopsis.desc","type":"muzzle"}');
    event.text('tacz:index/attachments/muzzle_silencer_sg.json', '{"name":"tacz.attachment.muzzle_silencer_sg.name","display":"tacz:muzzle_silencer_sg_display","data":"tacz:muzzle_silencer_sg_data","tooltip":"tacz.attachment.muzzle_silencer_sg.desc","type":"muzzle"}');
    event.text('tacz:index/attachments/muzzle_silencer_ursus.json', '{"name":"tacz.attachment.muzzle_silencer_ursus.name","display":"tacz:muzzle_silencer_ursus_display","data":"tacz:muzzle_silencer_ursus_data","tooltip":"tacz.attachment.muzzle_silencer_ursus.desc","type":"muzzle"}');
    event.text('tacz:index/attachments/muzzle_silencer_vulture.json', '{"name":"tacz.attachment.muzzle_silencer_vulture.name","display":"tacz:muzzle_silencer_vulture_display","data":"tacz:muzzle_silencer_vulture_data","tooltip":"tacz.attachment.muzzle_silencer_vulture.desc","type":"muzzle"}');
    event.text('tacz:index/attachments/muzzle_silencer_wraith.json', '{"name":"tacz.attachment.muzzle_silencer_wraith.name","display":"tacz:muzzle_silencer_wraith_display","data":"tacz:muzzle_silencer_wraith_data","tooltip":"tacz.attachment.muzzle_silencer_wraith.desc","type":"muzzle"}');
    event.text('tacz:index/attachments/oem_stock_heavy.json', '{"name":"tacz.attachment.oem_stock_heavy.name","display":"tacz:oem_stock_heavy_display","data":"tacz:oem_stock_heavy_data","tooltip":"tacz.attachment.oem_stock_heavy.desc","type":"stock","sort":1}');
    event.text('tacz:index/attachments/oem_stock_light.json', '{"name":"tacz.attachment.oem_stock_light.name","display":"tacz:oem_stock_light_display","data":"tacz:oem_stock_light_data","tooltip":"tacz.attachment.oem_stock_light.desc","type":"stock","sort":1}');
    event.text('tacz:index/attachments/oem_stock_tactical.json', '{"name":"tacz.attachment.oem_stock_tactical.name","display":"tacz:oem_stock_tactical_display","data":"tacz:oem_stock_tactical_data","tooltip":"tacz.attachment.oem_stock_tactical.desc","type":"stock","sort":1}');
    event.text('tacz:index/attachments/scope_1873_6x.json', '{"name":"tacz.attachment.scope_1873_6x.name","display":"tacz:scope_1873_6x_display","data":"tacz:scope_1873_6x_data","tooltip":"tacz.attachment.scope_1873_6x.desc","type":"scope","sort":1000}');
    event.text('tacz:index/attachments/scope_98k.json', '{"name":"tacz.attachment.scope_98k.name","display":"tacz:scope_98k_display","data":"tacz:scope_98k_data","tooltip":"tacz.attachment.scope_98k.desc","type":"scope","sort":100}');
    event.text('tacz:index/attachments/scope_acog_ta31.json', '{"name":"tacz.attachment.scope_acog_ta31.name","display":"tacz:scope_acog_ta31_display","data":"tacz:scope_acog_ta31_data","tooltip":"tacz.attachment.scope_acog_ta31.desc","type":"scope","sort":100}');
    event.text('tacz:index/attachments/scope_aug_default.json', '{"hidden":true,"name":"tacz.attachment.scope_aug_default.name","display":"tacz:scope_aug_default_display","data":"tacz:scope_aug_default_data","tooltip":"tacz.attachment.scope_aug_default.desc","type":"scope"}');
    event.text('tacz:index/attachments/scope_contender.json', '{"name":"tacz.attachment.scope_contender.name","display":"tacz:scope_contender_display","data":"tacz:scope_contender_data","tooltip":"tacz.attachment.scope_contender.desc","type":"scope","sort":1000}');
    event.text('tacz:index/attachments/scope_elcan_4x.json', '{"name":"tacz.attachment.scope_elcan_4x.name","display":"tacz:scope_elcan_4x_display","data":"tacz:scope_elcan_4x_data","tooltip":"tacz.attachment.scope_elcan_4x.desc","type":"scope","sort":100}');
    event.text('tacz:index/attachments/scope_hamr.json', '{"hidden":false,"name":"tacz.attachment.scope_hamr.name","display":"tacz:scope_hamr_display","data":"tacz:scope_hamr_data","tooltip":"tacz.attachment.scope_hamr.desc","type":"scope","sort":10}');
    event.text('tacz:index/attachments/scope_lpvo_1_6.json', '{"name":"tacz.attachment.scope_lpvo_1_6.name","display":"tacz:scope_lpvo_1_6_display","data":"tacz:scope_lpvo_1_6_data","tooltip":"tacz.attachment.scope_lpvo_1_6.desc","type":"scope","sort":100}');
    event.text('tacz:index/attachments/scope_mk5hd.json', '{"hidden":false,"name":"tacz.attachment.scope_mk5hd.name","display":"tacz:scope_mk5hd_display","data":"tacz:scope_mk5hd_data","tooltip":"tacz.attachment.scope_mk5hd.desc","type":"scope","sort":100}');
    event.text('tacz:index/attachments/scope_qmk152.json', '{"name":"tacz.attachment.scope_qmk152.name","display":"tacz:scope_qmk152_display","data":"tacz:scope_qmk152_data","tooltip":"tacz.attachment.scope_qmk152.desc","type":"scope","sort":100}');
    event.text('tacz:index/attachments/scope_retro_2x.json', '{"name":"tacz.attachment.scope_retro_2x.name","display":"tacz:scope_retro_2x_display","data":"tacz:scope_retro_2x_data","tooltip":"tacz.attachment.scope_retro_2x.desc","type":"scope","sort":100}');
    event.text('tacz:index/attachments/scope_standard_8x.json', '{"name":"tacz.attachment.scope_standard_8x.name","display":"tacz:scope_scout_display","data":"tacz:scope_scout_data","tooltip":"tacz.attachment.scope_standard_8x.desc","type":"scope","sort":100}');
    event.text('tacz:index/attachments/scope_vudu.json', '{"hidden":false,"name":"tacz.attachment.scope_vudu.name","display":"tacz:scope_vudu_display","data":"tacz:scope_vudu_data","tooltip":"tacz.attachment.scope_vudu.desc","type":"scope","sort":100}');
    event.text('tacz:index/attachments/shotgun_extended_mag_1.json', '{"name":"tacz.attachment.shotgun_extended_mag_1.name","display":"tacz:shotgun_extended_mag_1_display","data":"tacz:shotgun_extended_mag_1_data","tooltip":"tacz.attachment.shotgun_extended_mag_1.desc","type":"extended_mag","sort":10}');
    event.text('tacz:index/attachments/shotgun_extended_mag_2.json', '{"name":"tacz.attachment.shotgun_extended_mag_2.name","display":"tacz:shotgun_extended_mag_2_display","data":"tacz:shotgun_extended_mag_2_data","tooltip":"tacz.attachment.shotgun_extended_mag_2.desc","type":"extended_mag","sort":10}');
    event.text('tacz:index/attachments/shotgun_extended_mag_3.json', '{"name":"tacz.attachment.shotgun_extended_mag_3.name","display":"tacz:shotgun_extended_mag_3_display","data":"tacz:shotgun_extended_mag_3_data","tooltip":"tacz.attachment.shotgun_extended_mag_3.desc","type":"extended_mag","sort":10}');
    event.text('tacz:index/attachments/sight_552.json', '{"hidden":false,"name":"tacz.attachment.sight_552.name","display":"tacz:sight_552_display","data":"tacz:sight_552_data","tooltip":"tacz.attachment.sight_552.desc","type":"scope","sort":10}');
    event.text('tacz:index/attachments/sight_acro_pistol.json', '{"hidden":false,"name":"tacz.attachment.sight_acro_pistol.name","display":"tacz:sight_acro_pistol_display","data":"tacz:sight_acro_pistol_data","tooltip":"tacz.attachment.sight_acro_pistol.desc","type":"scope","sort":1}');
    event.text('tacz:index/attachments/sight_acro_rifle.json', '{"hidden":false,"name":"tacz.attachment.sight_acro_rifle.name","display":"tacz:sight_acro_rifle_display","data":"tacz:sight_acro_rifle_data","tooltip":"tacz.attachment.sight_acro_rifle.desc","type":"scope","sort":10}');
    event.text('tacz:index/attachments/sight_coyote.json', '{"name":"tacz.attachment.sight_coyote.name","display":"tacz:sight_coyote_display","data":"tacz:sight_coyote_data","tooltip":"tacz.attachment.sight_coyote.desc","type":"scope","sort":10}');
    event.text('tacz:index/attachments/sight_deltapoint_pistol.json', '{"hidden":false,"name":"tacz.attachment.sight_deltapoint_pistol.name","display":"tacz:sight_deltapoint_pistol_display","data":"tacz:sight_deltapoint_pistol_data","tooltip":"tacz.attachment.sight_deltapoint_pistol.desc","type":"scope","sort":1}');
    event.text('tacz:index/attachments/sight_deltapoint_rifle.json', '{"hidden":false,"name":"tacz.attachment.sight_deltapoint_rifle.name","display":"tacz:sight_deltapoint_rifle_display","data":"tacz:sight_deltapoint_rifle_data","tooltip":"tacz.attachment.sight_deltapoint_rifle.desc","type":"scope","sort":10}');
    event.text('tacz:index/attachments/sight_exp3.json', '{"name":"tacz.attachment.sight_exp3.name","display":"tacz:sight_exp3_display","data":"tacz:sight_exp3_data","tooltip":"tacz.attachment.sight_exp3.desc","type":"scope","sort":10}');
    event.text('tacz:index/attachments/sight_fastfire_pistol.json', '{"hidden":false,"name":"tacz.attachment.sight_fastfire_pistol.name","display":"tacz:sight_fastfire_pistol_display","data":"tacz:sight_fastfire_pistol_data","tooltip":"tacz.attachment.sight_fastfire_pistol.desc","type":"scope","sort":1}');
    event.text('tacz:index/attachments/sight_fastfire_rifle.json', '{"hidden":false,"name":"tacz.attachment.sight_fastfire_rifle.name","display":"tacz:sight_fastfire_rifle_display","data":"tacz:sight_fastfire_rifle_data","tooltip":"tacz.attachment.sight_fastfire_rifle.desc","type":"scope","sort":10}');
    event.text('tacz:index/attachments/sight_okp7.json', '{"hidden":false,"name":"tacz.attachment.sight_okp7.name","display":"tacz:sight_okp7_display","data":"tacz:sight_okp7_data","tooltip":"tacz.attachment.sight_okp7.desc","type":"scope","sort":10}');
    event.text('tacz:index/attachments/sight_p90.json', '{"name":"tacz.attachment.sight_p90.name","display":"tacz:sight_p90_display","data":"tacz:sight_p90_data","tooltip":"tacz.attachment.sight_p90.desc","type":"scope","hidden":true}');
    event.text('tacz:index/attachments/sight_pk06_pistol.json', '{"hidden":false,"name":"tacz.attachment.sight_pk06_pistol.name","display":"tacz:sight_pk06_pistol_display","data":"tacz:sight_pk06_pistol_data","tooltip":"tacz.attachment.sight_pk06_pistol.desc","type":"scope","sort":1}');
    event.text('tacz:index/attachments/sight_pk06_rifle.json', '{"hidden":false,"name":"tacz.attachment.sight_pk06_rifle.name","display":"tacz:sight_pk06_rifle_display","data":"tacz:sight_pk06_rifle_data","tooltip":"tacz.attachment.sight_pk06_rifle.desc","type":"scope","sort":10}');
    event.text('tacz:index/attachments/sight_rmr_dot.json', '{"name":"tacz.attachment.sight_rmr_dot.name","display":"tacz:sight_rmr_dot_display","data":"tacz:sight_rmr_dot_data","tooltip":"tacz.attachment.sight_rmr_dot.desc","type":"scope","sort":1}');
    event.text('tacz:index/attachments/sight_sro_dot.json', '{"name":"tacz.attachment.sight_sro_dot.name","display":"tacz:sight_sro_dot_display","data":"tacz:sight_sro_dot_data","tooltip":"tacz.attachment.sight_sro_dot.desc","type":"scope","sort":1}');
    event.text('tacz:index/attachments/sight_srs_02.json', '{"hidden":false,"name":"tacz.attachment.sight_srs_02.name","display":"tacz:sight_srs_02_display","data":"tacz:sight_srs_02_data","tooltip":"tacz.attachment.sight_srs_02.desc","type":"scope","sort":1}');
    event.text('tacz:index/attachments/sight_t1.json', '{"name":"tacz.attachment.sight_t1.name","display":"tacz:sight_t1_display","data":"tacz:sight_t1_data","tooltip":"tacz.attachment.sight_t1.desc","type":"scope","sort":10}');
    event.text('tacz:index/attachments/sight_t2.json', '{"name":"tacz.attachment.sight_t2.name","display":"tacz:sight_t2_display","data":"tacz:sight_t2_data","tooltip":"tacz.attachment.sight_t2.desc","type":"scope","sort":10}');
    event.text('tacz:index/attachments/sight_uh1.json', '{"name":"tacz.attachment.sight_uh1.name","display":"tacz:sight_uh1_display","data":"tacz:sight_uh1_data","tooltip":"tacz.attachment.sight_uh1.desc","type":"scope","sort":10}');
    event.text('tacz:index/attachments/sniper_extended_mag_1.json', '{"name":"tacz.attachment.sniper_extended_mag_1.name","display":"tacz:sniper_extended_mag_1_display","data":"tacz:sniper_extended_mag_1_data","tooltip":"tacz.attachment.sniper_extended_mag_1.desc","type":"extended_mag","sort":100}');
    event.text('tacz:index/attachments/sniper_extended_mag_2.json', '{"name":"tacz.attachment.sniper_extended_mag_2.name","display":"tacz:sniper_extended_mag_2_display","data":"tacz:sniper_extended_mag_2_data","tooltip":"tacz.attachment.sniper_extended_mag_2.desc","type":"extended_mag","sort":100}');
    event.text('tacz:index/attachments/sniper_extended_mag_3.json', '{"name":"tacz.attachment.sniper_extended_mag_3.name","display":"tacz:sniper_extended_mag_3_display","data":"tacz:sniper_extended_mag_3_data","tooltip":"tacz.attachment.sniper_extended_mag_3.desc","type":"extended_mag","sort":100}');
    event.text('tacz:index/attachments/stock_ak12.json', '{"name":"tacz.attachment.stock_ak12.name","display":"tacz:stock_ak12_display","data":"tacz:stock_ak12_data","tooltip":"tacz.attachment.stock_ak12.desc","type":"stock","sort":10}');
    event.text('tacz:index/attachments/stock_carbon_bone_c5.json', '{"name":"tacz.attachment.stock_carbon_bone_c5.name","display":"tacz:stock_carbon_bone_c5_display","data":"tacz:stock_carbon_bone_c5_data","tooltip":"tacz.attachment.stock_carbon_bone_c5.desc","type":"stock","sort":10}');
    event.text('tacz:index/attachments/stock_heavy_spas_12.json', '{"name":"tacz.attachment.stock_heavy_spas_12.name","display":"tacz:stock_heavy_spas_12_display","data":"tacz:stock_heavy_spas_12_data","tooltip":"tacz.attachment.stock_heavy_spas_12.desc","type":"stock","sort":11}');
    event.text('tacz:index/attachments/stock_hk_slim_line.json', '{"name":"tacz.attachment.stock_hk_slim_line.name","display":"tacz:stock_hk_slim_line_display","data":"tacz:stock_hk_slim_line_data","tooltip":"tacz.attachment.stock_hk_slim_line.desc","type":"stock","sort":10}');
    event.text('tacz:index/attachments/stock_m4ss.json', '{"name":"tacz.attachment.stock_m4ss.name","display":"tacz:stock_m4ss_display","data":"tacz:stock_m4ss_data","tooltip":"tacz.attachment.stock_m4ss.desc","type":"stock","sort":10}');
    event.text('tacz:index/attachments/stock_militech_b5.json', '{"name":"tacz.attachment.stock_militech_b5.name","display":"tacz:stock_militech_b5_display","data":"tacz:stock_militech_b5_data","tooltip":"tacz.attachment.stock_militech_b5.desc","type":"stock","sort":10}');
    event.text('tacz:index/attachments/stock_moe.json', '{"name":"tacz.attachment.stock_moe.name","display":"tacz:stock_moe_display","data":"tacz:stock_moe_data","tooltip":"tacz.attachment.stock_moe.desc","type":"stock","sort":10}');
    event.text('tacz:index/attachments/stock_ripstock.json', '{"name":"tacz.attachment.stock_ripstock.name","display":"tacz:stock_ripstock_display","data":"tacz:stock_ripstock_data","tooltip":"tacz.attachment.stock_ripstock.desc","type":"stock","sort":10}');
    event.text('tacz:index/attachments/stock_sba3.json', '{"name":"tacz.attachment.stock_sba3.name","display":"tacz:stock_sba3_display","data":"tacz:stock_sba3_data","tooltip":"tacz.attachment.stock_sba3.desc","type":"stock","sort":10}');
    event.text('tacz:index/attachments/stock_tactical_ar.json', '{"name":"tacz.attachment.stock_tactical_ar.name","display":"tacz:stock_tactical_ar_display","data":"tacz:stock_tactical_ar_data","tooltip":"tacz.attachment.stock_tactical_ar.desc","type":"stock","sort":10}');
    event.text('tacz:index/attachments/stock_tactical_spas_12.json', '{"name":"tacz.attachment.stock_tactical_spas_12.name","display":"tacz:stock_tactical_spas_12_display","data":"tacz:stock_tactical_spas_12_data","tooltip":"tacz.attachment.stock_tactical_spas_12.desc","type":"stock","sort":12}');
  });
}
